<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address line 3_addressLine3</name>
   <tag></tag>
   <elementGuidId>2854a3fc-f8f6-4131-8ccf-4751d49153fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressLine3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @id = 'addressLine3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89469706-b728-4bb6-a41d-693d5c9bdc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>512c22e7-c2c8-45a6-b4f6-aa2929b6ae30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressLine3</value>
      <webElementGuid>c80831fe-5eed-49d4-bec1-3fb2c0ff6062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>addressLine3</value>
      <webElementGuid>25131d84-3657-4d97-95d7-9a872da445d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>62e444ea-67d0-4d0b-88fc-1ae502a9731b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3afd5e98-605d-4428-9eda-3bad234926e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressLine3&quot;)</value>
      <webElementGuid>040b5ba1-ed8c-4eb0-8273-15c2758f2807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'addressLine3']</value>
      <webElementGuid>c9ac3f1a-bc00-4cdd-ac9f-79e44bba5a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressLine3']</value>
      <webElementGuid>05c98af7-2f4d-41c9-bdd8-3e3ddba679dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-address-lookup/div/div[3]/input</value>
      <webElementGuid>49a93a5b-18f4-4367-be06-659e41c8669f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
