<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Home telephone_client1hometelephone</name>
   <tag></tag>
   <elementGuidId>93920968-af08-4a87-8925-d7add1e95cdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1hometelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'client1hometelephone' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e84732af-d27d-4b5e-9d94-fe8b2e366955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>homeTelephone</value>
      <webElementGuid>535334ed-35b8-4683-8ed9-58fe580fd814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1hometelephone</value>
      <webElementGuid>f5ec7b20-8045-4061-bf72-b3ac0eae7d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c25377f8-32d0-445d-aa0b-48139a2ccea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>614854a2-1a91-46c9-81fb-8a35bfa2507e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03cf0400-527d-43f4-975b-631ef1768239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1hometelephone&quot;)</value>
      <webElementGuid>8a4ce6c0-f4ad-44e4-ab66-0791c5f43ea8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1hometelephone' and @type = 'text']</value>
      <webElementGuid>7a96818c-baed-4a4e-94ab-8be643d0c7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1hometelephone']</value>
      <webElementGuid>ad444c86-60f7-45f5-b298-2f57add4842b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[2]/input</value>
      <webElementGuid>b1732762-6278-4758-ae1a-53e37a313556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
