<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_gender1</name>
   <tag></tag>
   <elementGuidId>eafe0065-31b3-4340-b3d3-7764afbdf9aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1gendermale</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'client1gendermale' and @name = 'gender1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7aaac5dd-e9f6-4232-b7e0-29abff6351da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2e8e25d9-d3f9-4a9f-b488-d06a07286a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1gendermale</value>
      <webElementGuid>d8511947-038e-408d-ba27-ad860b81df5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>male</value>
      <webElementGuid>44175ec8-9517-4fcb-9433-c456eb27e33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>2200676e-ee5f-41ae-a622-848d1e348099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>74c9703f-6588-4a8a-96b3-2137251f7821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d679c706-d936-4fe7-912e-d93299d7c8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender1</value>
      <webElementGuid>a0d71a90-44d4-401b-b2ff-acc2a1ab8002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1gendermale&quot;)</value>
      <webElementGuid>7488b49c-1b36-43c2-aa31-3f73117746ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1gendermale' and @name = 'gender1']</value>
      <webElementGuid>ed01e769-1d1d-46a3-8611-24b59a4e1d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1gendermale']</value>
      <webElementGuid>0aa14671-7f8e-453b-b8c3-bf3ca24591b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>7635b743-9dd5-4321-85d2-2792b0a8e880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
