<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select titleMrMsMrsMissDrOther</name>
   <tag></tag>
   <elementGuidId>28d8e9b6-75f1-4907-97db-a631b94a243c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'client1title' and (text() = 'Select titleMrMsMrsMissDrOther' or . = 'Select titleMrMsMrsMissDrOther')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>09ed59f8-4b14-4b4c-8aa2-67e4bcb8f40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>4814ece0-d82a-4bf9-b462-eea94ed44c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1title</value>
      <webElementGuid>56bafbd4-16f3-455e-8c7b-584a03fd7424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c36bd295-980d-44e6-9cd2-66be9ab132b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f9f6993c-23e8-455d-94f3-9b67895a7866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select titleMrMsMrsMissDrOther</value>
      <webElementGuid>81e325e5-5218-4d42-916a-4d90f4d27f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1title&quot;)</value>
      <webElementGuid>399b81a9-6a12-4a20-8305-73f1128955e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1title' and (text() = 'Select titleMrMsMrsMissDrOther' or . = 'Select titleMrMsMrsMissDrOther')]</value>
      <webElementGuid>5c5a27d7-4dea-48b7-8922-f01153c99d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1title']</value>
      <webElementGuid>e8fc3307-b7af-4e3d-ada0-0bdee82f8788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title*'])[1]/following::select[1]</value>
      <webElementGuid>36ca6eae-3a6f-4093-9481-29158da1792e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal information'])[1]/following::select[1]</value>
      <webElementGuid>346bdecf-4357-4f28-a575-b977ae01dae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name/s*'])[1]/preceding::select[1]</value>
      <webElementGuid>c76ae02d-b350-4625-9e02-357aa0a824a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name*'])[1]/preceding::select[1]</value>
      <webElementGuid>0ec47a89-742a-43f0-947d-80952b2e1c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/select</value>
      <webElementGuid>aa783f36-12c8-4c22-8856-5d71274ce2fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
