<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_provisionForFamilyInCaseOfDeath</name>
   <tag></tag>
   <elementGuidId>b108e57c-b877-4129-8486-f975050f1890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#provisionForFamilyInCaseOfDeath-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='provisionForFamilyInCaseOfDeath-no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f3e2d51-aa66-43d2-b8f7-9444df2ee04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ca546ccc-e45f-4b13-adc7-3aea9401e208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>provisionForFamilyInCaseOfDeath-no</value>
      <webElementGuid>4ad798a3-9204-4c75-8f97-e838d1056f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>provisionForFamilyInCaseOfDeath</value>
      <webElementGuid>c88e423c-e955-419a-9ab8-3109f29085fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d4418313-2084-441b-8f78-0e7248fb513f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6cecc9bb-f5ef-44ec-b8d2-4a7ca8e3ab6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provisionForFamilyInCaseOfDeath</value>
      <webElementGuid>856ed313-9f64-4156-9ff4-a32a22084553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provisionForFamilyInCaseOfDeath-no&quot;)</value>
      <webElementGuid>19a1a0dc-0eb4-4155-b67f-5d804698b2fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='provisionForFamilyInCaseOfDeath-no']</value>
      <webElementGuid>9785cd04-5fb1-4a49-8c18-6108704a80e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input[2]</value>
      <webElementGuid>ec66c11f-1825-4ec6-a4b9-a2f7ff27a31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'provisionForFamilyInCaseOfDeath-no' and @name = 'provisionForFamilyInCaseOfDeath']</value>
      <webElementGuid>f9b1c85d-bdbe-42b7-b3ac-7bee3436848d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
