<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please select an option_continueToRec_a41e6b</name>
   <tag></tag>
   <elementGuidId>e894ff19-b3b1-4d29-89c7-597cc7531446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continueToReceiveIncomeInillness-yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='continueToReceiveIncomeInillness-yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d235e251-3f97-4060-aba0-8d0eac000477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8d887f33-7ad3-4605-bac1-c931e5c0eaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness-yes</value>
      <webElementGuid>631f2ff1-9a1f-4373-a1f2-f8eb5d1247d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness</value>
      <webElementGuid>1ea0e66b-5f4f-4a64-be0c-83b16683395e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2bb6dd9c-2e90-4402-ad9d-a678e35ab6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5cc5c497-ab25-4a5c-b2ae-070c196f399f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness</value>
      <webElementGuid>751f2c79-a618-4999-8bd7-0160087d7d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueToReceiveIncomeInillness-yes&quot;)</value>
      <webElementGuid>7a526ceb-317c-4dc3-b65e-ea95aa84945b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='continueToReceiveIncomeInillness-yes']</value>
      <webElementGuid>ef5fed3a-eace-443f-a9ec-2bfb9f976073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div[2]/div/div/input</value>
      <webElementGuid>2a0727dd-d593-4a2d-bfef-c24efe523920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'continueToReceiveIncomeInillness-yes' and @name = 'continueToReceiveIncomeInillness']</value>
      <webElementGuid>f6f98c9a-cc94-438a-9446-4bcc698cafd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
