<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expected retirement age_client1-emplo_dac0ea</name>
   <tag></tag>
   <elementGuidId>2cdbde84-215e-4853-a100-7b70564ca309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-employed-retirement-age</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-employed-retirement-age']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0fb0dcc-1e46-4a70-bba0-9f9d10d40da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-employed-retirement-age</value>
      <webElementGuid>ada6961d-eb5a-467b-a784-888cc105981e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>28d9bdff-29c5-4b49-9804-b1c7e14536ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expectedRetirementAge</value>
      <webElementGuid>894ddb4f-9823-46b4-8aa3-636e8c5bd0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>a720babe-1c92-4385-b0d3-664bac23f15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>44cddd88-6e88-4f9e-b108-3f8da01b6bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-employed-retirement-age&quot;)</value>
      <webElementGuid>1024699a-5a54-4c34-b386-6ccaaaa9024e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-employed-retirement-age']</value>
      <webElementGuid>edef9def-7127-43c2-98c8-a291456ad18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div/input</value>
      <webElementGuid>4a54fb57-ba96-428d-8ec8-fcf010fed6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-employed-retirement-age' and @type = 'number']</value>
      <webElementGuid>5ecd9e5f-0d08-4a88-af41-bac99858b225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
