<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What year will the mortgage be repaid_749b19</name>
   <tag></tag>
   <elementGuidId>d2ef2071-3156-4847-bc4e-3b977d1d508f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mortgageRepaidYear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mortgageRepaidYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac136597-464d-4ea3-b987-72f61846e084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82056f34-dfc2-4270-8de1-aabbc287ffd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY</value>
      <webElementGuid>d918b8d6-8062-4a17-842c-eb2039b30fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>Mortgage repaid year</value>
      <webElementGuid>b98597d7-9f40-4316-9ed2-93e73eaf549d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mortgageRepaidYear</value>
      <webElementGuid>60716317-4dc1-4fd5-8583-85972bbc9a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d192ca85-2760-4260-a31a-b5aacd2e0598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>94bc2042-9fce-47a4-8433-2c37d4838dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mortgageRepaidYear</value>
      <webElementGuid>a316ce8f-c175-45b2-82fd-c0324e26e289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>170d01e4-7543-4cd6-8d2a-03f51c653547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mortgageRepaidYear&quot;)</value>
      <webElementGuid>0d46d219-6dd7-4185-8a85-33a66e08ebe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mortgageRepaidYear']</value>
      <webElementGuid>6d96594c-670d-4691-bdb7-cba12a5adb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[5]/div[2]/div/input</value>
      <webElementGuid>52ac4838-ccc9-40f2-96b6-ead52219054d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'YYYY' and @id = 'mortgageRepaidYear']</value>
      <webElementGuid>41989dd8-a701-4dae-a6f9-6c477d696e9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
