<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Based on this description, do you thi_bdfd1b</name>
   <tag></tag>
   <elementGuidId>a4907bb7-ffbc-4c0f-8220-16e30adf5fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-politically-exposed-yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-politically-exposed-yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5eedf0a7-f91d-4442-9e3f-8b18b3c2d2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>87454b5b-8912-4912-a8ed-9017460897b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-politically-exposed-yes</value>
      <webElementGuid>28cfcac2-bb58-434c-90b1-2fcd84aa7b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isPoliticallyExposedPerson</value>
      <webElementGuid>7339b2a0-078d-468b-831e-ec7615787510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d068e5fb-c11b-412d-af9c-b60eb47a668d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08477722-be78-4c12-8969-d66be8903762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isPoliticallyExposedPerson1</value>
      <webElementGuid>ad04b537-f189-4a2f-9c56-72c02d50e518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-politically-exposed-yes&quot;)</value>
      <webElementGuid>fc0c33d3-3c60-4816-bdcf-a59d6e406790</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-politically-exposed-yes']</value>
      <webElementGuid>8592d1d2-99c7-4150-b8ff-0838d0e6bf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/input</value>
      <webElementGuid>acef1c8c-02d7-46e1-a7b7-04a56193e516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-politically-exposed-yes' and @name = 'isPoliticallyExposedPerson1']</value>
      <webElementGuid>e88aad03-e03f-40f7-907f-a134c1b8bce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
