<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile telephone_client1mobiletelephone</name>
   <tag></tag>
   <elementGuidId>4e8354f9-a74c-47f6-b008-d4569a3b9504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1mobiletelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1mobiletelephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc27cf1c-d736-403c-b246-39a4fda1b399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>fdbcc149-d7a6-42c8-ab9a-93c20cb6f0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1mobiletelephone</value>
      <webElementGuid>2f886e95-92d4-45dd-b3e3-4675b79cc45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca5cc9fb-0c55-4804-924a-4b9d3c8dfead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5cded482-4d89-43c7-adb9-5dbe8ef325ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a298ac9b-72c5-46c6-ae0a-5aa38f5fa1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1mobiletelephone&quot;)</value>
      <webElementGuid>4c74aab9-47d0-4537-ae05-a32896737e1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1mobiletelephone']</value>
      <webElementGuid>67640b0b-622f-4390-8c1f-bd10c5ae17b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[3]/input</value>
      <webElementGuid>c62a0b38-e076-49a4-bbc7-1660887862ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1mobiletelephone' and @type = 'text']</value>
      <webElementGuid>cbe56fb4-4df3-4d7f-9ef5-70c8a0241f4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
