<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Communication and Marketing Preferenc_8fce92</name>
   <tag></tag>
   <elementGuidId>3d637ada-2f67-4ff9-afa2-9df8e0e7d57f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-contact-post</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-contact-post']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a527fb8-35a1-48cb-9bf0-5d06cf8a6ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isContactableViaPost</value>
      <webElementGuid>11d52aa3-364d-4012-932d-47a50ded0994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7c979430-e6e7-41c8-b322-e23300454cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-contact-post</value>
      <webElementGuid>32fce525-efac-42ad-b555-c1a5ed4dcd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3482f73a-3888-4292-b738-fedf9a0282f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>255ccb6a-5733-4074-befb-464c44ee5723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-contact-post&quot;)</value>
      <webElementGuid>dee71bc0-6e3c-4120-b9ee-b5a1e2d0f1a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-contact-post']</value>
      <webElementGuid>ed37400b-13dd-4ac5-afe8-2d913cd5f325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>2367bcfc-811d-4183-8ca8-b8d5d5d14150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'client1-contact-post']</value>
      <webElementGuid>468a2738-0b31-45ea-ab81-50078fc5dab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
