<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Or Please tick all applicable_five-po_b5c783</name>
   <tag></tag>
   <elementGuidId>f8ba90c0-3c24-4f4b-a9b5-bb0cd2669622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#five-point-check-haveHealthAndWelfarePowerOfAttorney</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='five-point-check-haveHealthAndWelfarePowerOfAttorney']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>510cd12d-84c4-401a-874a-45c1322108be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>47b4abfc-d25f-4965-aedd-0c37700644d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>five-point-check-haveHealthAndWelfarePowerOfAttorney</value>
      <webElementGuid>a2dbe7fd-befc-4b3b-b374-94d0333bb0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>haveHealthAndWelfarePowerOfAttorney</value>
      <webElementGuid>084e1d60-555d-469f-ab1d-6fbb5818ae9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0f468aaf-551b-45ab-9924-f5bb71078894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>acef8c65-5c05-4bd7-ba8b-28650176d879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;five-point-check-haveHealthAndWelfarePowerOfAttorney&quot;)</value>
      <webElementGuid>5152de54-6d76-4989-b107-ed3299faa95f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='five-point-check-haveHealthAndWelfarePowerOfAttorney']</value>
      <webElementGuid>bb180027-fe25-4e54-bd87-6a35909fda7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[3]/div/input</value>
      <webElementGuid>37b55cbc-b684-49b4-919d-ac621c854b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'five-point-check-haveHealthAndWelfarePowerOfAttorney']</value>
      <webElementGuid>4d4f3e0a-8a7c-4951-9fd6-7e0df6e029bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
