<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Disagree_riskQuestionsClient129Answer120</name>
   <tag></tag>
   <elementGuidId>38874252-3a32-4c91-a306-698525ed063d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#riskQuestionsClient129Answer120</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='riskQuestionsClient129Answer120']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6682a90d-7438-4e53-8299-48376d3d5e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>304d305e-c941-4f23-98b1-ec9c000c8763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>94552872-18ae-4450-aba6-3a688e95fb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>riskQuestionsClient129Answer120</value>
      <webElementGuid>97c91706-5344-46a6-a431-b2eefcd5360e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>18ac0f4e-5baa-45a0-bc9b-71f5b9179e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riskQuestionsClient129Answer120&quot;)</value>
      <webElementGuid>5f0d983a-7464-4bc1-a732-04cc738458c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='riskQuestionsClient129Answer120']</value>
      <webElementGuid>d167ca9f-98d4-4809-9cc5-330d25c87eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[3]/input</value>
      <webElementGuid>c86232a4-06d3-44e4-b9c7-1514e75cd159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'riskQuestionsClient129Answer120']</value>
      <webElementGuid>1d60973e-0f33-420a-9ea1-dce9fe62c994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
