<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work telephone_client1worktelephone</name>
   <tag></tag>
   <elementGuidId>5463e8ba-68dc-4ab1-bd37-b42380cdb4ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1worktelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1worktelephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c64230a-c8b8-47e6-bbef-17afc0f70cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>workTelephone</value>
      <webElementGuid>097fc4b0-1210-493d-92f1-34669d25c6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1worktelephone</value>
      <webElementGuid>93781166-4409-42fb-b247-69572e57d31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac248248-a0de-411d-8322-6540c8f8b156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>312d4dd8-0120-4422-952a-412be844eaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ff5ef9d5-1d7d-4dfd-98b1-972fdb2c05d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1worktelephone&quot;)</value>
      <webElementGuid>26aff5d5-055f-49f8-8390-94823d7438bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1worktelephone']</value>
      <webElementGuid>2980ca4c-4c6b-42ec-af49-1d3a4e7bd9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[4]/input</value>
      <webElementGuid>ca9baf9c-b01c-4cbf-8b50-c386e45a539e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1worktelephone' and @type = 'text']</value>
      <webElementGuid>2099588f-2e68-48a0-b71b-5c2f106d1b25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
