<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Disagree_riskQuestionsClient125Answer100</name>
   <tag></tag>
   <elementGuidId>3340dd14-e62e-4b49-b332-01ba5956394a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#riskQuestionsClient125Answer100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='riskQuestionsClient125Answer100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ba2903c-9994-400f-963f-99bffee1a0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>94483d3e-ffde-43aa-ba16-df008ad1d842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d82778ac-ba1c-4cc8-92cd-b24250a28305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>riskQuestionsClient125Answer100</value>
      <webElementGuid>6a264a26-6521-4141-bc98-5d4deb76acfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c72bfb85-2a36-4021-a76a-69c3a93bcd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riskQuestionsClient125Answer100&quot;)</value>
      <webElementGuid>21b84a1b-4820-4d2c-9187-44505823da82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='riskQuestionsClient125Answer100']</value>
      <webElementGuid>b38b4aed-1e4a-45bb-8e8d-faeeb1c7e05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dynamic-questionnaire/div/div[6]/div[3]/input</value>
      <webElementGuid>181f5565-877b-41ed-9ba1-fe4b71b549eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'riskQuestionsClient125Answer100']</value>
      <webElementGuid>5e49bc22-9e21-43a1-a46f-82576f34087e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
