<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OccupationJob title_client1-employed-_f9375d</name>
   <tag></tag>
   <elementGuidId>91d4e6fe-ea9b-4052-b294-1fabe1eb3c47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-employed-occupation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-employed-occupation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a545c0dc-9e34-439a-b180-bdb34afe7bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-employed-occupation</value>
      <webElementGuid>14a6cc3f-16b6-4c8e-9ec3-e0ebc7edbf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84510da7-fb29-446d-bdbc-862f6d2cd4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>occupation</value>
      <webElementGuid>39e47a49-5573-4e07-b743-7ca8adef1466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e861fbb8-22a2-4a8b-b537-419dabd5f407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c0412919-2fc5-45e6-a6aa-e66c6594304e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-employed-occupation&quot;)</value>
      <webElementGuid>a01b7147-b7dd-464e-ab26-aebffd721fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-employed-occupation']</value>
      <webElementGuid>19a78a53-4bf4-407a-ad4a-1f03397be5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div[2]/input</value>
      <webElementGuid>ad65ad62-4ccb-47a4-bd41-5627a93c4243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-employed-occupation' and @type = 'text']</value>
      <webElementGuid>4734ebf5-1a95-4bb2-81d5-a3c2fcf5f36a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
