<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select NationalityBritishAfghaniAlba_eb0c08</name>
   <tag></tag>
   <elementGuidId>d3e498dd-acdc-4e17-b381-f0654254eaa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-nat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client1-nat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e0603f06-c39a-4eb8-b711-25f0eba5469a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-nat</value>
      <webElementGuid>5dbcc1ab-d7af-4a47-a688-54bbd9fec632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nationality</value>
      <webElementGuid>ce53a77a-0626-4a25-9cce-36b98663b50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f2208496-a377-40c6-82ed-44ac73eda634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f69f07e3-1b45-468d-8e11-8fc111d078cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean</value>
      <webElementGuid>d323dda7-bb1c-42ee-b413-0ddc3ed19344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-nat&quot;)</value>
      <webElementGuid>00581be5-5420-4c59-9225-3fdcf3fe7ae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1-nat']</value>
      <webElementGuid>df06710f-0473-4826-873d-9eecc6c7c093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/following::select[1]</value>
      <webElementGuid>6e780d7c-b61f-4a00-ab79-900c3a7c3a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality/ Personal Identifier/s'])[1]/following::select[1]</value>
      <webElementGuid>5a22868e-9737-4279-b4ae-959306236e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax residency'])[1]/preceding::select[1]</value>
      <webElementGuid>ec55cb2e-b636-4496-8d33-86297553b35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First country of tax residency'])[1]/preceding::select[1]</value>
      <webElementGuid>75af322a-4710-4254-b9d0-65ce0bfdef7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/select</value>
      <webElementGuid>36d5c714-42c2-49ef-a4cb-d3632c135e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1-nat' and (text() = 'Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean' or . = 'Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean')]</value>
      <webElementGuid>e9bcdf82-0871-48aa-8274-2a9c89d7ab31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
