<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Summary</name>
   <tag></tag>
   <elementGuidId>c7b533d2-da7c-4051-b6b0-133c8c7cca01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tab-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft application'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79fd2fab-1350-44e3-ba59-e7f9d78e1dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-title</value>
      <webElementGuid>50fa12c3-502f-406d-9ac0-1a1c3a59dd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>bb1eac22-5bba-45bf-89d6-ddbb7b9a36dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Summary </value>
      <webElementGuid>0b9d0641-1328-4613-8d8a-371198cf9fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-create-application[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-l&quot;]/div[@class=&quot;col-12 mt-xl mb-xxl&quot;]/app-tabs[1]/div[@class=&quot;tabs--container row&quot;]/div[@class=&quot;tabs--header col-12&quot;]/ul[1]/li[@class=&quot;tab-item ng-star-inserted&quot;]/span[@class=&quot;tab-title&quot;]</value>
      <webElementGuid>afb3f9d2-dcb0-4aa4-8bc4-3c41df2c3159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft application'])[1]/following::span[1]</value>
      <webElementGuid>9db57044-2f91-419b-9f6f-5a53b1c04153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to all applications'])[1]/following::span[1]</value>
      <webElementGuid>d1828903-b247-4afd-8a44-cb6a8f4eddb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Details'])[1]/preceding::span[2]</value>
      <webElementGuid>2550d432-bec3-4430-8cb4-9f1f2ba6cef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Risk Questions'])[1]/preceding::span[4]</value>
      <webElementGuid>60edd833-e5e7-4a73-974e-fa9e263e7c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Summary']/parent::*</value>
      <webElementGuid>c9586d3d-2e86-4b77-9d13-e856dcb885eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>d0c7b85c-a729-4cf8-b8e5-afede6d664b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Summary' and (text() = 'Summary ' or . = 'Summary ')]</value>
      <webElementGuid>084db5fc-c0dd-4736-969d-8680f40574a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
