<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Details_client1-politically-exposed-text</name>
   <tag></tag>
   <elementGuidId>fdad4a3f-3365-437b-b4bd-37eebad50232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-politically-exposed-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='client1-politically-exposed-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>18994fe9-71ad-4722-971a-e3c2236cf84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-politically-exposed-text</value>
      <webElementGuid>cd50e5d0-a93e-405d-af71-19892c2f4f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>politicallyExposedPersonDetails</value>
      <webElementGuid>9de3995c-737d-44e8-b55d-fba4a1722d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>8cb5167b-3099-4819-bf2b-f5efac996398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f4a40acd-9c7d-4b7a-a265-91bc2c2c3859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-politically-exposed-text&quot;)</value>
      <webElementGuid>367967ca-1152-4591-9bd1-22d06e75dc3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='client1-politically-exposed-text']</value>
      <webElementGuid>0fd5c8fa-939d-4847-80b0-22cb0f547618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>52c477d2-ea6d-4d84-b4b8-6e762ded7563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'client1-politically-exposed-text']</value>
      <webElementGuid>5c607c6d-7f47-417b-80b4-01b3926424d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
