<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>additionalDetailsStatus</name>
   <tag></tag>
   <elementGuidId>9efe3ab7-d0ca-406f-b1d5-c2962212e03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-select.ng-untouched.ng-pristine.ng-valid.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[(text() = 'UnpublishedPublishSigned off' or . = 'UnpublishedPublishSigned off')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>377c7652-a014-45b9-a5f6-3478d7d9376e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>additionalDetailsStatus</value>
      <webElementGuid>365fb6f4-5989-4bc7-9f8c-27a755fa846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>b2cfad40-9bfb-4a55-bbf1-c671c93d85ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4e312ef8-358b-4f1f-9ce4-f5cc73b86a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UnpublishedPublishSigned off</value>
      <webElementGuid>be7e095e-c8c5-439f-a635-526dd1443d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publish-settings-overlay&quot;)/app-publish-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;bg-white&quot;]/div[@class=&quot;container pt-xl pb-xl mb-xxl&quot;]/div[@class=&quot;flex-grid flex-grid--2&quot;]/div[@class=&quot;flex-grid__cell ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;row alternate-table-rows&quot;]/div[@class=&quot;row col-12&quot;]/div[@class=&quot;col-5 p-xs pr-l&quot;]/select[@class=&quot;form-select ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>6f583210-5871-40e6-86d2-de3bc075417b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'UnpublishedPublishSigned off' or . = 'UnpublishedPublishSigned off')]</value>
      <webElementGuid>43388266-dd89-435b-9b79-2daa5db3308a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='publish-settings-overlay']/app-publish-settings/div/div/div[2]/div/div/div[4]/div[2]/select</value>
      <webElementGuid>96d0b94b-1d51-4673-9c98-06548832d327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional details'])[1]/following::select[1]</value>
      <webElementGuid>e5840e0d-6022-4d9e-b37d-b93fc6035c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client details'])[2]/following::select[2]</value>
      <webElementGuid>6a61ad96-4c04-4585-9a6f-dd1de66c1f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial details'])[2]/preceding::select[1]</value>
      <webElementGuid>76648d58-9282-41b4-b645-e1132fe2d194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Risk questions'])[1]/preceding::select[2]</value>
      <webElementGuid>f1c86eac-0813-41a4-b815-8476dec1149e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/select</value>
      <webElementGuid>d2a9dbb0-5bf3-44a9-931f-95be63c35964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
