<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>applicable type</name>
   <tag></tag>
   <elementGuidId>d2ac5c69-b278-4528-8fad-d228ff48757d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mortgageType-interest-only</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'mortgageType-interest-only' and @name = 'mortgageType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45cec1de-936b-4fd0-b6b2-65aa2a628d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>906faa34-9237-42ce-a140-eca33529cdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mortgageType-interest-only</value>
      <webElementGuid>25791222-6385-41dc-b6b3-77df81b37613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mortgageType</value>
      <webElementGuid>7b26267c-b3ce-4778-bd8e-630d8a811fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3e066d1c-0d1e-4b92-a1e0-d430980f7ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>158c5291-e7a9-44fa-bdbf-be6a68d8a07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mortgageType</value>
      <webElementGuid>acbf4684-56f3-4352-9a10-2876c9b81142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mortgageType-interest-only&quot;)</value>
      <webElementGuid>74311be5-f071-49ca-8ccb-b9a0e5cea6b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'mortgageType-interest-only' and @name = 'mortgageType']</value>
      <webElementGuid>7d1cbdae-596e-492a-b65d-465518ab8bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mortgageType-interest-only']</value>
      <webElementGuid>55b38fe6-ac74-4fcb-b83b-c3a8eb58607d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/section/div[3]/div[2]/div/div/input</value>
      <webElementGuid>dac9b53d-3b46-48cb-8c84-cd9b45312087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
