<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Communication and Marketing Preferenc</name>
   <tag></tag>
   <elementGuidId>5c42712f-502c-4a14-90ff-bb677cc05454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-contact-post</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox' and @id = 'client1-contact-post']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3ec445b-6e36-4861-8f9a-c92a82f3a436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isContactableViaPost</value>
      <webElementGuid>72db1cc8-4541-42df-9d57-f8ec1a5a8241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e4e650dc-9fc2-485a-9d23-ab0292921c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-contact-post</value>
      <webElementGuid>5beb67e6-7c58-420c-8c0f-58ea29f39a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a4253c51-a88a-4a2e-999b-e3d179ba4ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>065860e9-18ee-4a23-be93-205511f024c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-contact-post&quot;)</value>
      <webElementGuid>d45eeac2-0c9c-4bf4-8a0f-48f2f4c52287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'client1-contact-post']</value>
      <webElementGuid>9cf9ea2d-df87-4a87-8098-a3d94bca923c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-contact-post']</value>
      <webElementGuid>794a33d2-f8b1-4e70-82c4-6d5f207bdd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>b6c916e4-be0e-453f-829a-be3d92cd38e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
