<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continueToReceiveIncomeInillness</name>
   <tag></tag>
   <elementGuidId>1d264789-5226-4d1c-9427-91ff79aa57c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continueToReceiveIncomeInillness-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'continueToReceiveIncomeInillness-no' and @name = 'continueToReceiveIncomeInillness']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb297558-c93d-4d0a-90bb-0ac76e50c048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e2a0a4b5-6943-4dc4-aeec-1a59a184e82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness-no</value>
      <webElementGuid>b4176f45-0044-47cd-9eb3-97f6c3401e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness</value>
      <webElementGuid>9ab7d8d9-03c5-4280-adcb-628b2d2a0ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3d3a487c-25c5-4391-9d13-7b4fc4db6ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eda0cbf1-1f69-42db-be63-3f4b81ba5743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness</value>
      <webElementGuid>6abeff64-5345-441b-9181-af1f4e7b3405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueToReceiveIncomeInillness-no&quot;)</value>
      <webElementGuid>9d781db9-cdd0-4b7b-9258-df2efc0f9655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'continueToReceiveIncomeInillness-no' and @name = 'continueToReceiveIncomeInillness']</value>
      <webElementGuid>8a85c5f0-0d2c-4f35-bdfe-209fac990a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='continueToReceiveIncomeInillness-no']</value>
      <webElementGuid>b5fb1ffc-3e89-40d4-b91c-7bf19ec3cd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div[2]/div/div/input[2]</value>
      <webElementGuid>959e2c2b-f0fd-426a-9523-0c1ffed3f340</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
