<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DefinedBenefitsOrFinalSalaryScheme1</name>
   <tag></tag>
   <elementGuidId>db717967-9d6b-49d5-b2b7-e33e840de57e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2' and @name = 'isMemberOfDefinedBenefitsOrFinalSalaryScheme1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a830b8d6-12ec-474b-b1c6-5bb56a8c9e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>39d0e4a7-d45a-4be2-bb43-5fd85b5fd94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2</value>
      <webElementGuid>338ff396-2e34-40eb-96c4-310d65b2048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalaryScheme</value>
      <webElementGuid>7c25321b-672d-4e16-9ff8-6df9f819b97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>aa01d28c-bf05-4727-9972-f0ef8b2317d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94845f9c-fa3f-4bc6-af92-766f8e02055d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalaryScheme1</value>
      <webElementGuid>e1faf493-84fe-425a-a834-bb7d60bd5977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2&quot;)</value>
      <webElementGuid>1bd2f88c-e978-44c2-b1ef-c38c8a348635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2' and @name = 'isMemberOfDefinedBenefitsOrFinalSalaryScheme1']</value>
      <webElementGuid>a52c5d50-df81-4107-8549-6100c9d637dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2']</value>
      <webElementGuid>efa29964-6a04-4756-98d4-af89b800e62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/input</value>
      <webElementGuid>9302730e-5548-4873-a215-f68997f9b748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
