<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Disagree_riskQuestionsClient125Answer100</name>
   <tag></tag>
   <elementGuidId>8aab0146-1e78-4e72-88b1-8f424486de19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#riskQuestionsClient125Answer100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'riskQuestionsClient125Answer100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4780e789-7cee-43fe-a178-4c4997c2d5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>305480d9-b2ea-44f0-9ad2-19d7bc47ad8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9272b972-01f6-4eb4-956a-8a3a6fd7f051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>riskQuestionsClient125Answer100</value>
      <webElementGuid>a6c5cb27-70c3-47e2-8f3c-6562f132f320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7d055cc0-e3f2-41ee-8343-e7e757cdbcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riskQuestionsClient125Answer100&quot;)</value>
      <webElementGuid>8dc9fc20-00d2-49ac-a9e2-8a73503e0637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'riskQuestionsClient125Answer100']</value>
      <webElementGuid>53914ada-dffd-4e47-8044-3c332971cfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='riskQuestionsClient125Answer100']</value>
      <webElementGuid>e440b8c6-3830-4800-a3ae-c4492864f51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dynamic-questionnaire/div/div[6]/div[3]/input</value>
      <webElementGuid>8d1af045-76c0-4598-8c27-cff8fb9f582b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
