<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Driving licence number_client1</name>
   <tag></tag>
   <elementGuidId>914b512c-e867-44cd-b38b-9d6354d0a8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-driving-passport-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'client1-driving-passport-no' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>053ac55d-90ac-4bf3-9aba-7bfbedf64e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-driving-passport-no</value>
      <webElementGuid>8c8c111c-102b-4a02-9a2c-a56daa048805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac4d6f93-7347-4dc8-bede-3ccdb6c34db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>verificationIdNumber</value>
      <webElementGuid>77cd5a4a-58da-4a4a-86f5-44e8b5bca907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ab19f408-c375-45f7-8a00-956c41debbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>164b6486-6e00-4b8c-9a8a-41a792bdbb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-driving-passport-no&quot;)</value>
      <webElementGuid>c9aeed4e-d557-4df4-b35e-4fa389cb8e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-driving-passport-no' and @type = 'text']</value>
      <webElementGuid>32886788-7e50-44ce-9d26-786aba9cc63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-driving-passport-no']</value>
      <webElementGuid>081bf549-fcd1-469b-8ca4-c6c0a4bee3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div[2]/div/input</value>
      <webElementGuid>0681bddb-6720-4808-87c8-89422e5436cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
