<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HaveUptodateWill</name>
   <tag></tag>
   <elementGuidId>aed81372-6318-4c0d-ac96-a2d86336471a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#haveUptodateWill-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'haveUptodateWill-no' and @name = 'haveUptodateWill']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85c24de4-0d8c-447d-a794-85f9de73e42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fc62edd7-fcc4-40c9-a525-2c60bbadedb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>haveUptodateWill-no</value>
      <webElementGuid>3d7f9c4b-d15c-4d60-8783-8cdbc9b27ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>haveUptodateWill</value>
      <webElementGuid>f0d345d1-7350-4ad0-a6fb-9dc90104da2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>19bcda7a-5e76-47d2-9afe-e8fa41f0238b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>673f77e9-b4c2-4da4-a316-541f7cda9156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>haveUptodateWill</value>
      <webElementGuid>daf29e57-99a7-4a35-81f5-9b642a37946a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;haveUptodateWill-no&quot;)</value>
      <webElementGuid>802553c1-bb74-42bf-ac6f-bb285179d80b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'haveUptodateWill-no' and @name = 'haveUptodateWill']</value>
      <webElementGuid>1aa363ce-a18f-4e53-8067-4fdbb00d16b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='haveUptodateWill-no']</value>
      <webElementGuid>f8b896ba-ae6e-412a-b1f3-f3e7504607b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input[2]</value>
      <webElementGuid>c7d91f9b-c3c2-4be1-a5f8-1b9182cd9c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
