<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home telephone_client1hometelephone</name>
   <tag></tag>
   <elementGuidId>bdaafd33-e733-4012-aa49-7b7d67e21946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1hometelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'client1hometelephone' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd42b1b9-4038-4623-95a3-1fa18656bd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>homeTelephone</value>
      <webElementGuid>69d88970-3345-46c1-b7ff-04cb1f761f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1hometelephone</value>
      <webElementGuid>94f921e7-d078-453d-b149-6e1885216952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e11e700-fb14-4541-9fdb-8198e6bd17b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>52c39302-df9a-4264-adbb-ac7872527894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>61d0c067-3b59-4401-afbc-e64edc4d41fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1hometelephone&quot;)</value>
      <webElementGuid>f4c1fec0-90cf-439b-b77f-40851675be98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1hometelephone' and @type = 'text']</value>
      <webElementGuid>e38000e3-973e-49c6-93c6-6a8343c878bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1hometelephone']</value>
      <webElementGuid>406d3b7f-8166-45fe-81b9-09ff7c9d3bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[2]/input</value>
      <webElementGuid>81fa283b-9c53-4b84-a21a-b6fe29ec4ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
