<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passport_verificationIdType1</name>
   <tag></tag>
   <elementGuidId>18682f29-0d31-4669-93ef-322dc7988319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-driving-licence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'client1-driving-licence' and @name = 'verificationIdType1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eb43d6c-a2dc-4c10-a136-07928d8df649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>049b6286-7941-4013-bce4-5a10cf9cb9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-driving-licence</value>
      <webElementGuid>9f4933f5-f976-4d84-a351-c6307c6029ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Driving licence</value>
      <webElementGuid>9b180451-894c-4e04-8cbe-5d96e257cefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>verificationIdType</value>
      <webElementGuid>5cbddaa5-b745-471f-a704-b106f2dae9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b9fd7d72-3b62-433f-a0b9-a295d5cb3a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e930195-8cd2-4615-a4b3-914bf5a656f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verificationIdType1</value>
      <webElementGuid>c40f6382-24c0-41de-8722-d7877b1b0e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-driving-licence&quot;)</value>
      <webElementGuid>fc21ceac-7cbf-4346-9bed-13642cde0a41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-driving-licence' and @name = 'verificationIdType1']</value>
      <webElementGuid>db71408b-4500-4d2a-9711-832428e6f448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-driving-licence']</value>
      <webElementGuid>909d1925-2909-4ed2-bb21-47ae49cfdb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div/input[2]</value>
      <webElementGuid>a12e3f7b-7b18-4404-9d20-11130bbd09d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
