<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_isPoliticallyExposedPerson1</name>
   <tag></tag>
   <elementGuidId>f59906e9-c201-4a70-ae75-f769192ee54a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-politically-exposed-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'client1-politically-exposed-no' and @name = 'isPoliticallyExposedPerson1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fb603a2-64ff-4e72-9d02-0b6547e9dca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>af2ebbb2-1552-48e5-b1e1-b9069988c3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-politically-exposed-no</value>
      <webElementGuid>7fb170f0-d411-47ac-aab4-d59da7bb9968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isPoliticallyExposedPerson</value>
      <webElementGuid>b3e091ce-f5c7-458c-ac8b-7cea780ceff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>baf13d5d-7f71-4d7b-8a90-a55705f008e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cb7e729c-a1e3-456b-8698-f67db5a1fa0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isPoliticallyExposedPerson1</value>
      <webElementGuid>9d5946bb-173d-4f56-91c6-d6ec5bb4d6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-politically-exposed-no&quot;)</value>
      <webElementGuid>1315c539-b797-4436-be8c-c48a851b5265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-politically-exposed-no' and @name = 'isPoliticallyExposedPerson1']</value>
      <webElementGuid>742c72da-449f-41e2-8f4c-9943afa706b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-politically-exposed-no']</value>
      <webElementGuid>d5b1d8bd-5f9d-47f8-bc54-3e536ea6ef64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/input[2]</value>
      <webElementGuid>c2fdb539-1e2b-416a-9372-031d0ffaa975</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
