<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>isOtherFinancialInformationAvailable1</name>
   <tag></tag>
   <elementGuidId>634ed59f-8b78-40e7-a3a8-f37fc3a05ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otherInformationClient1Option2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'otherInformationClient1Option2' and @name = 'isOtherFinancialInformationAvailable1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7c5a5e0-5523-4080-b6f4-14a9533db999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d18035bb-2056-4eb9-bae1-7586973299b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherInformationClient1Option2</value>
      <webElementGuid>5df551d7-857f-4488-a6a3-dd4d0fbca78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isOtherFinancialInformationAvailable</value>
      <webElementGuid>dfea6ebb-e624-474a-9474-fa29d5dbc6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>dd1ad958-8800-4a79-8241-e6e8dc8c5006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>56d90fca-25c7-4ded-8572-2e8a3e08a3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isOtherFinancialInformationAvailable1</value>
      <webElementGuid>8e611c33-1449-43d2-a509-d512b2c866d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherInformationClient1Option2&quot;)</value>
      <webElementGuid>95b5bff7-050e-404e-aa55-353a1d4197bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'otherInformationClient1Option2' and @name = 'isOtherFinancialInformationAvailable1']</value>
      <webElementGuid>e53aadd2-466c-41f0-92ce-358eb778b663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherInformationClient1Option2']</value>
      <webElementGuid>6c040678-219f-401b-959a-75c5da54e4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>b8caa56a-b326-41ce-b45e-eac8f4da947e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
