<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mobile telephone_client1mobiletelephone</name>
   <tag></tag>
   <elementGuidId>12d13aa4-892a-4b23-a800-839b306c9ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1mobiletelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'client1mobiletelephone' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c58f145-4924-446a-ba87-16faa074bfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>8a7a0857-d379-481a-87b6-937c1b6cac7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1mobiletelephone</value>
      <webElementGuid>3c6a9e75-13ee-4775-a2dd-6163522863d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4085b98-4d27-4516-a8fb-c1aeeb46b478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>83c16cf0-00ac-4062-9a52-147f3be899d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c7f85c5d-dab0-4cd6-be7d-7605afa038e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1mobiletelephone&quot;)</value>
      <webElementGuid>ef649d22-1e16-4e5d-9697-d26c22393b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1mobiletelephone' and @type = 'text']</value>
      <webElementGuid>225c4a4d-05b3-481d-9754-cad1339899c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1mobiletelephone']</value>
      <webElementGuid>4ef6ad23-f598-406a-990b-baa81bbcff84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[3]/input</value>
      <webElementGuid>b094ca08-ff0e-4aa6-9e78-cfd6c6425c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
