<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nature of business employment_client1</name>
   <tag></tag>
   <elementGuidId>17d52744-306e-4c46-9051-12d11ae5553d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-employed-business-nature</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'client1-employed-business-nature' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74fdb8d0-1558-479d-956c-df8e060372a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-employed-business-nature</value>
      <webElementGuid>d94bc256-ab10-4b6e-be86-b2155a3bb9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64c1e6a4-a9ef-4784-baef-8fad7218879a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>natureOfBusiness</value>
      <webElementGuid>9a659cf6-757b-40a3-a231-b9c979cf44af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0b65fa1b-1c18-44c3-81c7-f9cb96f2e3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>87880157-0423-4883-a82b-97606932b134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-employed-business-nature&quot;)</value>
      <webElementGuid>4f5e5311-67e6-4d1b-9173-8a2cfc31964c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-employed-business-nature' and @type = 'text']</value>
      <webElementGuid>64d50658-056e-4340-90fb-b831bd5e0331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-employed-business-nature']</value>
      <webElementGuid>2b60b3a0-6d9e-4535-9bf9-b4ba77629165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div[2]/div[4]/input</value>
      <webElementGuid>c67e4037-07f6-4a7c-8e84-d688bb504d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
