<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NetAnnualIncomeChangeIn</name>
   <tag></tag>
   <elementGuidId>fb238636-30d4-4e72-8f99-9ea60772d01b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#incomeChangeClient1Option1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'incomeChangeClient1Option1' and @name = 'willNetAnnualIncomeChangeInNext12Months1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8be23d2-632a-4b71-b591-632dc5e2471c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0dc9b87a-1547-40c1-a052-051c8012f44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incomeChangeClient1Option1</value>
      <webElementGuid>21c191a8-80c3-42ee-849e-d29ea1d2ea41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>willNetAnnualIncomeChangeInNext12Months</value>
      <webElementGuid>b83f39dc-6269-4a08-8dc3-6a2578361c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b3588819-f436-48f5-8fb1-5b6575785d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>58cdf1f4-644f-4661-a3e1-4dec6de6a247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>willNetAnnualIncomeChangeInNext12Months1</value>
      <webElementGuid>9099008e-68e3-42c5-b92d-728650aa4eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incomeChangeClient1Option1&quot;)</value>
      <webElementGuid>12090cf6-e796-4936-96e8-102d7209a737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'incomeChangeClient1Option1' and @name = 'willNetAnnualIncomeChangeInNext12Months1']</value>
      <webElementGuid>18b87471-5c2d-428e-8b84-e87a8072ee8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='incomeChangeClient1Option1']</value>
      <webElementGuid>fb4d5094-6988-4708-8d91-0217eafb841c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[2]/div[2]/div/div/input</value>
      <webElementGuid>10ce711e-9372-4cd7-a45b-e6d988b33699</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
