<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Occupational Qualifications</name>
   <tag></tag>
   <elementGuidId>d7a07509-a76d-431a-a257-6d0d9885e6e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-financial-experience-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'client1-financial-experience-no' and @name = 'hasQualifications1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0214dc4e-97c4-43b9-997f-46f4f6d474ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>55006f20-a383-4f62-9daf-c811b1e76806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-financial-experience-no</value>
      <webElementGuid>ae2213f0-2b65-477c-ac07-fad2b112bba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>hasQualifications</value>
      <webElementGuid>a8693175-fe7f-45fb-aed4-d479de736651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>03cb3e21-2b4a-495d-a556-c3f876db3a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f5cd98a7-5c92-4d9a-a932-fb9bd638b2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hasQualifications1</value>
      <webElementGuid>478503f8-87e2-419f-8c66-8d725698c6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-financial-experience-no&quot;)</value>
      <webElementGuid>ab5da6bc-1cd5-4630-b287-db28ee8acc27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-financial-experience-no' and @name = 'hasQualifications1']</value>
      <webElementGuid>b55d1a76-68c8-47a9-98db-48dc89d56469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-financial-experience-no']</value>
      <webElementGuid>f0072a88-fcbd-43a6-ad90-c890aca2bd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[2]</value>
      <webElementGuid>bc6b62ba-6bf9-4c87-886a-56c0100ae38f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
