<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unsure_liabilitiesInCaseOfDeath</name>
   <tag></tag>
   <elementGuidId>0480530a-deb1-4f6a-a3e6-7105f640cb8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#liabilitiesInCaseOfDeath-yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @id = 'liabilitiesInCaseOfDeath-yes' and @name = 'liabilitiesInCaseOfDeath']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8219d16-779b-43f0-9fbd-6ea44ed88a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d1f09e46-29af-4e09-9745-cf7cc34e4f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>liabilitiesInCaseOfDeath-yes</value>
      <webElementGuid>3bd61162-2425-4d9e-b33d-ba0d12f7ba70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>liabilitiesInCaseOfDeath</value>
      <webElementGuid>021dfb68-c5b8-4e95-8bea-67f96a6efac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3cad459b-78d1-4d06-8dd6-0f8ce0546274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8da32a0c-5c40-483a-9c8a-959576530d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>liabilitiesInCaseOfDeath</value>
      <webElementGuid>84021135-b1e2-405a-8db8-aa4af3f2d476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;liabilitiesInCaseOfDeath-yes&quot;)</value>
      <webElementGuid>0386c7b6-2ce4-4ee9-a4bb-f9d8852eeccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'liabilitiesInCaseOfDeath-yes' and @name = 'liabilitiesInCaseOfDeath']</value>
      <webElementGuid>eaf34daf-4e68-4135-b1b5-c7e692630cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='liabilitiesInCaseOfDeath-yes']</value>
      <webElementGuid>e423beee-0002-4942-b374-d7a9695c0ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[4]/div[2]/div/div/input</value>
      <webElementGuid>d0df33cf-6d82-4d14-ad6e-0f663672fb37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
