<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work telephone_client1worktelephone</name>
   <tag></tag>
   <elementGuidId>967248a6-b95b-4a27-b1d1-acac1e65844e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1worktelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'client1worktelephone' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adabd30d-fec6-488b-a9e8-13b741277484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>workTelephone</value>
      <webElementGuid>e9e34735-f90e-4cec-a9af-f63ae41738fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1worktelephone</value>
      <webElementGuid>c7a445c1-3a73-4a47-a1cd-6dad7b2d1017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dea8e524-dafd-4645-8bac-b7581390b641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0fdb7d1d-13e5-4cee-ab17-3d3bcf05993f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c4b4cf9f-ada5-4450-8b8e-2a4a568772d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1worktelephone&quot;)</value>
      <webElementGuid>d28ca4d1-ea4c-49c3-8efb-b495bd366f4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1worktelephone' and @type = 'text']</value>
      <webElementGuid>e8b73c7d-9b15-4d34-9b93-ba389ad6a69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1worktelephone']</value>
      <webElementGuid>2b152c07-92ec-4cb8-a3de-327d34e5150c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[4]/input</value>
      <webElementGuid>f890b95d-ff09-48b5-9d58-884b0f5234cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
