<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ok_healthCondition1</name>
   <tag></tag>
   <elementGuidId>35f60253-e06c-44f7-b0c0-61df59e81bbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='client1-health-bad'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.ng-invalid.ng-dirty.ng-touched > div.form-checkbox > #client1-health-bad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76a8f806-310b-46d3-97e1-ee90c0d2deca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cf5fc11f-8c0a-4ef6-ac9b-ced9ff4cdfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-health-bad</value>
      <webElementGuid>e55df434-da47-4d7f-b5a3-165bfbd29aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>healthCondition</value>
      <webElementGuid>211a8b6b-51cc-49e7-a92c-7e33d8c8e5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-dirty ng-valid ng-touched</value>
      <webElementGuid>692c948d-109f-44c3-ab7f-e6b3457845a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c69910a6-c490-4ee5-9733-b1d3331827fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>healthCondition1</value>
      <webElementGuid>754f330c-c3f7-4f62-84cd-3f040c07168d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-create-application[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-l&quot;]/div[@class=&quot;col-12 mt-xl mb-xxl&quot;]/app-tabs[1]/div[@class=&quot;tabs--container row&quot;]/div[@class=&quot;tabs--body col-12&quot;]/app-tab[11]/div[1]/app-retirement-planning-details[1]/div[@class=&quot;container p-0 bg-white box-shadow-grey&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/section[@class=&quot;row pl-l pt-m pb-m&quot;]/div[@class=&quot;col-5&quot;]/div[@class=&quot;form-group ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;form-checkbox&quot;]/input[@id=&quot;client1-health-bad&quot;]</value>
      <webElementGuid>a5ff592c-6e83-4545-8bb1-61136d4671b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='client1-health-bad'])[3]</value>
      <webElementGuid>04ef590b-5f40-4721-aedf-a5802d10b156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tab[11]/div/app-retirement-planning-details/div[2]/form/section[2]/div/div/div/input[3]</value>
      <webElementGuid>3aeafe5b-52ef-435a-9de4-0565da42724a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-health-bad' and @name = 'healthCondition1']</value>
      <webElementGuid>3a52ea25-e64e-4de1-811b-0f6e8eda9d28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
