<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_good_healthCondition1</name>
   <tag></tag>
   <elementGuidId>b9d3bfb2-613c-4fab-a211-0b356f712032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='client1-health-ok'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.ng-invalid.ng-dirty.ng-touched > div.form-checkbox > #client1-health-ok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eea28ab4-c934-467b-bf96-b5ae647f6374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>381d395e-9145-4c55-9645-bc64f3c4014e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-health-ok</value>
      <webElementGuid>a2edf994-dc2f-4af0-9c3d-43dd535287ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>healthCondition</value>
      <webElementGuid>1a43c90b-75ca-4837-a67f-5ca273911d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-dirty ng-valid ng-touched</value>
      <webElementGuid>9669d4fe-1e4c-4a0a-abd3-1059d86d667d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bde3e5f9-52ac-4808-a3b5-068f31c1ae76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>healthCondition1</value>
      <webElementGuid>98efdad0-e781-44f9-a5c4-775b4a61bd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-create-application[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-l&quot;]/div[@class=&quot;col-12 mt-xl mb-xxl&quot;]/app-tabs[1]/div[@class=&quot;tabs--container row&quot;]/div[@class=&quot;tabs--body col-12&quot;]/app-tab[11]/div[1]/app-retirement-planning-details[1]/div[@class=&quot;container p-0 bg-white box-shadow-grey&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/section[@class=&quot;row pl-l pt-m pb-m&quot;]/div[@class=&quot;col-5&quot;]/div[@class=&quot;form-group ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;form-checkbox&quot;]/input[@id=&quot;client1-health-ok&quot;]</value>
      <webElementGuid>8e48c84b-6df6-4f9b-9fe4-ecc9009c39a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='client1-health-ok'])[3]</value>
      <webElementGuid>8ceec0ce-d5e7-423b-9664-2a7226c410ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tab[11]/div/app-retirement-planning-details/div[2]/form/section[2]/div/div/div/input[2]</value>
      <webElementGuid>005111e5-8885-4fa0-94eb-0d4cc4de05a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-health-ok' and @name = 'healthCondition1']</value>
      <webElementGuid>5826b054-593e-463b-aa14-da463d0967f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
