<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_guarantee10</name>
   <tag></tag>
   <elementGuidId>7ba19c5d-9c62-4c6f-b9e5-9546f02044f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type = 'radio' and @id = '_guaranteeclient10' and @name = 'guarantee10'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e3792fe-3af9-4619-9afe-b5ed3ac11f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0ebd0f0a-e354-430f-b21c-f1c6d2099515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>guarantee</value>
      <webElementGuid>71fb838a-47c2-415b-b989-e76655b6cd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-dirty ng-valid ng-touched</value>
      <webElementGuid>c0ecdfcf-4e87-42cf-8e8b-25004787ea6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_guaranteeclient10</value>
      <webElementGuid>db3cf8eb-ee7f-42ee-85ac-b179e2b96299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>391c35f1-6b09-43be-acd7-2df7ec0bc9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guarantee10</value>
      <webElementGuid>9b75b06e-8703-4b4b-957f-0dcfe7f92666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-create-application[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-l&quot;]/div[@class=&quot;col-12 mt-xl mb-xxl&quot;]/app-tabs[1]/div[@class=&quot;tabs--container row&quot;]/div[@class=&quot;tabs--body col-12&quot;]/app-tab[11]/div[1]/app-retirement-planning-details[1]/div[@class=&quot;container p-0 bg-white box-shadow-grey&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/fieldset[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;row form-group pl-l pr-l&quot;]/div[@class=&quot;col-12&quot;]/defined-contribution-pension[1]/table[@class=&quot;mat-table ng-invalid ng-dirty ng-touched&quot;]/tbody[@class=&quot;font-bodysmall ng-star-inserted&quot;]/tr[@class=&quot;mat-row ng-invalid ng-star-inserted ng-dirty ng-touched&quot;]/td[@class=&quot;mat-cell column-center&quot;]/div[@class=&quot;form-checkbox&quot;]/input[@id=&quot;_guaranteeclient10&quot;]</value>
      <webElementGuid>9c0d439e-bd2a-4d4f-8e64-b978b5d97ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='_guaranteeclient10'])[2]</value>
      <webElementGuid>f523e773-bc43-440c-91cd-8d3309d474ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div[2]/input[2]</value>
      <webElementGuid>d2821c5b-e655-4741-b7a1-0ae4915e4ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '_guaranteeclient10' and @name = 'guarantee10']</value>
      <webElementGuid>7cc518e1-2673-4916-ab4c-21824df88a66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
