<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__guarantee10</name>
   <tag></tag>
   <elementGuidId>dc494349-84e8-4cf9-ae79-2d9ecf930227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@type = 'radio' and @formcontrolname = 'guarantee' and @id = '_guaranteeclient10' and @name = 'guarantee10'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_guaranteeclient10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2eaf2466-4747-4115-a7a1-e57a97a07c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0a6d8ac8-62cd-4009-a556-24570eb948b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>guarantee</value>
      <webElementGuid>72e8b3d9-b12e-4ed3-a712-57d095eade3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3079647a-2229-4f7f-97c2-fd851104eb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_guaranteeclient10</value>
      <webElementGuid>267fb3b0-45f8-47a4-9d34-b629faf1b6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>48b5ff3a-9298-4e49-aaeb-8809c5b663dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guarantee10</value>
      <webElementGuid>d92dabca-9ed2-453a-bfef-d25734aa6383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-create-application[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-l&quot;]/div[@class=&quot;col-12 mt-xl mb-xxl&quot;]/app-tabs[1]/div[@class=&quot;tabs--container row&quot;]/div[@class=&quot;tabs--body col-12&quot;]/app-tab[11]/div[1]/app-retirement-planning-details[1]/div[@class=&quot;container p-0 bg-white box-shadow-grey&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/fieldset[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;row form-group pl-l pr-l&quot;]/div[@class=&quot;col-12&quot;]/defined-contribution-pension[1]/table[@class=&quot;mat-table ng-invalid ng-dirty ng-touched&quot;]/tbody[@class=&quot;font-bodysmall ng-star-inserted&quot;]/tr[@class=&quot;mat-row ng-invalid ng-star-inserted ng-dirty ng-touched&quot;]/td[@class=&quot;mat-cell column-center&quot;]/div[@class=&quot;form-checkbox&quot;]/input[@id=&quot;_guaranteeclient10&quot;]</value>
      <webElementGuid>cc8eed82-c793-4a55-8f0f-e66035feaa28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_guaranteeclient10']</value>
      <webElementGuid>c262bb42-c5dd-4a4e-91b6-dc982bb50a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div[2]/input</value>
      <webElementGuid>6fe47be2-5e0a-4feb-bbb7-ce2ed28305ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '_guaranteeclient10' and @name = 'guarantee10']</value>
      <webElementGuid>ff7f6bc9-35a2-4cb9-96a4-200126936ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
