<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_hasQualifications1</name>
   <tag></tag>
   <elementGuidId>2c981c6d-39d5-4944-8fd5-dbc4c42f2eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-financial-experience-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-financial-experience-no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be256527-2eea-45c7-90d3-c1c80bb520e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1cd6fc82-1696-4890-a321-cb5c7c797c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-financial-experience-no</value>
      <webElementGuid>053174c1-f69e-4df4-a194-05b4c9273469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>hasQualifications</value>
      <webElementGuid>300eba00-94d7-4ff1-93b2-fd1d7ab8d685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3146d5c2-6380-4e66-b98b-ec594f01f1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>589d56e3-1a26-4ea7-9919-cbe6fb22d917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hasQualifications1</value>
      <webElementGuid>eeaae23d-ea50-49ea-95c3-391b1936f323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-financial-experience-no&quot;)</value>
      <webElementGuid>7e61a25f-73e0-4f91-90a4-46552c5a0fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-financial-experience-no']</value>
      <webElementGuid>6833b4f6-e8da-44a6-87f8-5eb6b40245d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[2]</value>
      <webElementGuid>e4e7d96e-ebf8-4ff7-8825-04a19707fbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-financial-experience-no' and @name = 'hasQualifications1']</value>
      <webElementGuid>5b0681be-bd03-42ec-9484-bc5fa86668f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
