<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_haveUptodateWill</name>
   <tag></tag>
   <elementGuidId>c1a8e2b8-89df-4b95-b7e7-f7168ce2ddc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#haveUptodateWill-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='haveUptodateWill-no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f0896c9-cdb0-42a0-a170-287b8252fdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5235058f-a1d6-4522-8d9f-4b4f570007dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>haveUptodateWill-no</value>
      <webElementGuid>1bead3ef-31c7-487a-b521-c121baa0c3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>haveUptodateWill</value>
      <webElementGuid>50045f3b-0733-4c75-a598-0b04f1b44587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>04f0d43f-5e85-481e-8300-f0aaf1327935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>56cfa750-0b90-4636-ae8e-e06967fdae80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>haveUptodateWill</value>
      <webElementGuid>e4420afe-2b04-44a9-9729-8056f680e906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;haveUptodateWill-no&quot;)</value>
      <webElementGuid>13ed081d-428a-42d8-84b0-26d0d8164a3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='haveUptodateWill-no']</value>
      <webElementGuid>df649e7a-f165-484f-9005-5629c218514b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input[2]</value>
      <webElementGuid>4b4f9d21-b549-4749-b2a2-6d2a2da888e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'haveUptodateWill-no' and @name = 'haveUptodateWill']</value>
      <webElementGuid>94ce7cf8-2041-404e-9495-a97ede0ee5a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
