<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_continueToReceiveIncomeInillness</name>
   <tag></tag>
   <elementGuidId>c546b71d-2436-49d3-84b7-1fbf00b85b1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continueToReceiveIncomeInillness-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='continueToReceiveIncomeInillness-no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d013c031-f23b-4607-b6df-71c4b3c71762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d7e34777-3f93-4e1e-bc9b-0a5f93b63a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness-no</value>
      <webElementGuid>c52ee162-28b8-4ae4-a6d7-e68f09651291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness</value>
      <webElementGuid>ec9714bc-5ef1-45c1-9654-8125f5857469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-dirty ng-valid ng-touched</value>
      <webElementGuid>c77a6ace-5093-41aa-81a9-6070c16b7049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c1b62c01-623c-45d2-902e-667db51ac12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness</value>
      <webElementGuid>caec1ccf-9fbe-402d-ab60-b6fec5285f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueToReceiveIncomeInillness-no&quot;)</value>
      <webElementGuid>b78804e8-1b79-42f9-9896-8d9717ea67de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='continueToReceiveIncomeInillness-no']</value>
      <webElementGuid>4628c04b-4462-4860-8910-a50a8d754212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div[2]/div/div/input[2]</value>
      <webElementGuid>91d16810-aa00-4665-aa02-1741bf4bef3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'continueToReceiveIncomeInillness-no' and @name = 'continueToReceiveIncomeInillness']</value>
      <webElementGuid>883147f6-bfce-4262-ac50-f10fb019a27c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
