<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_provisionForFamilyInCaseOfDeath</name>
   <tag></tag>
   <elementGuidId>73f54503-373d-4adf-a3d9-b9a67ac3cba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#provisionForFamilyInCaseOfDeath-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='provisionForFamilyInCaseOfDeath-no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf6fef3c-ad23-4340-bc09-dc63c0eff086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1a1fe710-5957-476a-bfde-3f76a7c6ffe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>provisionForFamilyInCaseOfDeath-no</value>
      <webElementGuid>aa5205ee-654c-4fb5-b265-e153cbf4f82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>provisionForFamilyInCaseOfDeath</value>
      <webElementGuid>d610e9f6-cb37-4a30-932e-c9e0fbad8898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>fb45536e-27cb-4e71-b0de-2a5a34f2b7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6ac37cae-57fe-49ea-8b19-34f30420d7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provisionForFamilyInCaseOfDeath</value>
      <webElementGuid>6bffd8fd-8f16-412a-b084-b15b64e2aa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provisionForFamilyInCaseOfDeath-no&quot;)</value>
      <webElementGuid>2f09b042-f89b-4c8e-b456-23a14ff61cbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='provisionForFamilyInCaseOfDeath-no']</value>
      <webElementGuid>99c0d0a6-0fe4-4592-972a-e3389ca14d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input[2]</value>
      <webElementGuid>ad83d7f5-d86f-44c7-a452-50e7c836f492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'provisionForFamilyInCaseOfDeath-no' and @name = 'provisionForFamilyInCaseOfDeath']</value>
      <webElementGuid>2696e068-810c-40ab-9cc5-0618d1bad09d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
