<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Power and Financial Affairs Lasting P_88d934</name>
   <tag></tag>
   <elementGuidId>68ff7a90-7f5b-4302-a42b-61a5dd25e6bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#five-point-check-haveEnduringPowerOfAttorney</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='five-point-check-haveEnduringPowerOfAttorney']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f652f40-5c7d-44cd-b497-8b8fb2e47416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>687eb39b-2329-416a-b162-01caf63ed1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>five-point-check-haveEnduringPowerOfAttorney</value>
      <webElementGuid>be9cf921-fd77-4e6b-9a33-28908dc54dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>haveEnduringPowerOfAttorney</value>
      <webElementGuid>0062b6c4-c59a-4fbf-9703-dfd54dc3c344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4283c64b-dfe8-44a9-b03b-ef077d5ee0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7d9d9c70-c50b-4c31-8ace-b5c5c92b5ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;five-point-check-haveEnduringPowerOfAttorney&quot;)</value>
      <webElementGuid>01155a2d-387e-4272-b579-56cefad8401c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='five-point-check-haveEnduringPowerOfAttorney']</value>
      <webElementGuid>a8d1c4d6-45d1-4b8b-bdc3-c715e7ad1e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/input</value>
      <webElementGuid>2cac1fa3-79b3-4a40-9843-37f051c12108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'five-point-check-haveEnduringPowerOfAttorney']</value>
      <webElementGuid>9e1405af-5e3f-4af6-b800-b320b874a17c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
