<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Communication and Marketing Preferenc_b744b6</name>
   <tag></tag>
   <elementGuidId>ed94d483-2582-400a-92a3-5de4819274da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-all-communications</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-all-communications']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbca8d12-7ee2-46b7-bbaf-754fa3b9473d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>hasOptedInMarketingUpdates</value>
      <webElementGuid>4a4aba18-220f-453d-9c5c-7f44e3a9c87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>801073e5-3c57-4e35-be73-461a43dd61ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-all-communications</value>
      <webElementGuid>8f342f0f-d100-4c06-b22c-bff456e4d818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6942b723-96e3-4436-b307-9f221bf21c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f953fc2-4f98-4b46-b746-e24938bdf5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-all-communications&quot;)</value>
      <webElementGuid>555bd17c-5ca2-4b2a-869c-2a2728c70478</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-all-communications']</value>
      <webElementGuid>b6d28ac3-547e-47d9-a6e3-74eb4267e74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>198bff3e-9b71-4aaf-b481-7a52ad29d209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'client1-all-communications']</value>
      <webElementGuid>69da8c3f-504d-4ac0-9658-b0b8af33a286</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
