<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Health and Welfare Lasting Power of A_f44e7f</name>
   <tag></tag>
   <elementGuidId>6ef00cb4-4602-4479-a70c-64ced15a57c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#five-point-check-havePowerAndFinancePowerOfAttorney</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='five-point-check-havePowerAndFinancePowerOfAttorney']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c4a0030-afaa-4dfa-869e-d162c730db04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6a7f73cb-1e45-4c6e-9dd7-52e74094df68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>five-point-check-havePowerAndFinancePowerOfAttorney</value>
      <webElementGuid>6cfa06cc-8c79-429c-8c46-bb4c7ca4fff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>havePowerAndFinancePowerOfAttorney</value>
      <webElementGuid>57aca49f-ebd7-442f-9e2e-5720f7b063ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2286bdae-fed9-4e49-b76a-f86e2dfafc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>83ea48f8-de03-485a-a605-4cb8b9e866c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;five-point-check-havePowerAndFinancePowerOfAttorney&quot;)</value>
      <webElementGuid>4f33cdad-157a-4ac6-a6ff-34515ea8c9e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='five-point-check-havePowerAndFinancePowerOfAttorney']</value>
      <webElementGuid>b97bf4ca-42ca-44cf-9293-e258eab19192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/input</value>
      <webElementGuid>37858117-76fd-4de6-a707-7e6fb8e1b610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'five-point-check-havePowerAndFinancePowerOfAttorney']</value>
      <webElementGuid>ac88e027-a53a-43c7-96ad-790c023f5faa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
