<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_willNetAnnualIncomeChangeInNext12Months1</name>
   <tag></tag>
   <elementGuidId>b2c76757-3c8c-484c-b7be-70aa6de6bbac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#incomeChangeClient1Option2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='incomeChangeClient1Option2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>346c21f0-9535-4f8a-ae72-6ac9de7abe5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>de8d9d8f-1b90-478e-8b71-b3d3c59f8d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incomeChangeClient1Option2</value>
      <webElementGuid>624c66a5-8d3c-4a3d-9c27-aa852e70d371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>willNetAnnualIncomeChangeInNext12Months</value>
      <webElementGuid>332dd5c4-f059-4242-98a7-b6243bed1f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b82d83fd-60d8-4d74-95bc-3b5adfa17a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>360536a1-9e74-4a99-b492-efb83a6adbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>willNetAnnualIncomeChangeInNext12Months1</value>
      <webElementGuid>4cd7247f-b2ad-4790-8df1-3d08123836dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incomeChangeClient1Option2&quot;)</value>
      <webElementGuid>50af6911-6086-49d1-9219-9067ba38cc63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='incomeChangeClient1Option2']</value>
      <webElementGuid>59746a32-c936-42da-b697-95b942c56735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>b28619a9-87c7-45e3-b71e-7f86292fd32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'incomeChangeClient1Option2' and @name = 'willNetAnnualIncomeChangeInNext12Months1']</value>
      <webElementGuid>6b01b1b3-ef8d-4c8c-8b22-e58aea23c5e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
