<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile telephone_client1mobiletelephone</name>
   <tag></tag>
   <elementGuidId>5ee685b5-ea80-43d7-8106-500aa8237f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1mobiletelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1mobiletelephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a2e9b61-625c-416b-bd0b-8897eb3d7648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>9d4b878c-77f3-4ca9-8a3c-d02d095ee595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1mobiletelephone</value>
      <webElementGuid>ab1c4373-6937-4431-b777-c1be680bb24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>233c6d16-d21a-4fff-8e86-7dd9099501a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8451ff90-24fe-44f7-bde5-004f6bb2e9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6b5e0283-8943-404c-b527-c10757913b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1mobiletelephone&quot;)</value>
      <webElementGuid>7357bbe6-2112-41f7-b885-7643826e7180</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1mobiletelephone']</value>
      <webElementGuid>a669bb3e-4dd2-4fc9-b603-60ea3ffd81be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[3]/input</value>
      <webElementGuid>9999ad2b-35ef-4bda-be3b-0a3d94990e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1mobiletelephone' and @type = 'text']</value>
      <webElementGuid>6d62c775-f4ea-401b-aef7-8904cddb206f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
