<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What year will the mortgage be repaid_749b19</name>
   <tag></tag>
   <elementGuidId>1fdb6464-613e-4c11-a6b2-64c45f8d584b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mortgageRepaidYear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mortgageRepaidYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61bd373a-8e95-488b-a95d-b75502c6c8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f375613-9d42-4d05-bbbd-d9ffa1ca7361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY</value>
      <webElementGuid>91772632-bb20-4c70-9744-b043a9f4ab43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>Mortgage repaid year</value>
      <webElementGuid>9b3860ec-c3dd-4dba-9252-6940b9a40b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mortgageRepaidYear</value>
      <webElementGuid>cb267623-5a83-4f11-8061-2f2e579573da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d4269e57-eec5-4bd2-997c-f792177b19f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f465488d-7087-4efe-ae65-47e3c145e73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mortgageRepaidYear</value>
      <webElementGuid>074da5ed-592d-4b1b-9f2d-a3beb2b8f096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>655a0c21-20ef-436f-b167-0b062c535a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mortgageRepaidYear&quot;)</value>
      <webElementGuid>b16d1769-112e-42f3-a4fb-1672331827e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mortgageRepaidYear']</value>
      <webElementGuid>245fc1ee-362d-48e5-a7dc-334a37465e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[5]/div[2]/div/input</value>
      <webElementGuid>0a81ab84-f948-466f-9bc2-f60dfefb6db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'YYYY' and @id = 'mortgageRepaidYear']</value>
      <webElementGuid>14a20cfb-8a9a-419f-8510-761027b8dfd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
