<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_isMemberOfDefinedBenefitsOrFinalS_81c75e</name>
   <tag></tag>
   <elementGuidId>665d8002-2e80-4e60-8b96-850224f2cfc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f78c2f3-c9f9-4782-8d91-62a10a07484f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>47b7f327-173f-4ef3-ad35-d06fade24a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2</value>
      <webElementGuid>8aae0f67-56e6-4f59-9846-2ca1a4d03119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalaryScheme</value>
      <webElementGuid>b9658ff3-4b53-499a-a577-3142f777df55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f67938aa-6e7e-432c-8587-2085e2c12855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>78edb846-76d2-428d-8c89-10c207393e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalaryScheme1</value>
      <webElementGuid>89dc69a6-6444-4f2e-acd1-643b3f79bed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2&quot;)</value>
      <webElementGuid>fb6a1d68-2869-4e9a-a10a-42d758353945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2']</value>
      <webElementGuid>40ea134b-4e07-414d-a83c-8db4edb97c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/input</value>
      <webElementGuid>b3acad73-1bd4-4b9f-bd7d-68f78cdb53ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option2' and @name = 'isMemberOfDefinedBenefitsOrFinalSalaryScheme1']</value>
      <webElementGuid>186ceebc-e05f-48d9-a433-892bd13aa42f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
