<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TownCity_town</name>
   <tag></tag>
   <elementGuidId>95ca2552-cce1-4d3b-8eb3-ada184470857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#town</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='town']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7144416b-02b7-4147-87fc-ec58474daab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>942afdfb-63d7-4aa1-be2a-9096457d0b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>town</value>
      <webElementGuid>2edf7aac-2873-40b2-982e-ac19243a8785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>town</value>
      <webElementGuid>10002955-bfd5-4027-9267-f3bf07819b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>43b88328-8dce-46fa-aedc-27f48a7c2706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6c7e6dfa-f821-4fc4-a81a-aa75191f2224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;town&quot;)</value>
      <webElementGuid>3a3d1654-7b33-4f24-9668-751237028b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='town']</value>
      <webElementGuid>15eabbf9-acb4-4702-bf4f-4c23a5f31947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-address-lookup/div/div[4]/input</value>
      <webElementGuid>bc56da50-3fbd-4836-80b3-a4f0caf91b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'town']</value>
      <webElementGuid>0c3ea4b3-9c17-4c5d-923e-61c9c8379e7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
