<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Communication and Marketing Preferenc_b744b6</name>
   <tag></tag>
   <elementGuidId>ed94d483-2582-400a-92a3-5de4819274da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-all-communications</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-all-communications']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd5b386c-39a5-4cb6-ad18-77c50afbc5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>hasOptedInMarketingUpdates</value>
      <webElementGuid>6febb15d-4bbb-42ee-88ef-7edda4701f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3daccb83-7dbf-4c62-a8aa-689ecf7b508f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-all-communications</value>
      <webElementGuid>f9fa47a3-3191-45b4-85fb-44c419fcc6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a311b4d3-8a31-44bd-9ad8-92fea1400ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a187aab8-cfd5-4e14-b4ce-88b119118c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-all-communications&quot;)</value>
      <webElementGuid>c606b878-024d-4e94-8b25-4bf9f876fcb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-all-communications']</value>
      <webElementGuid>20f9980b-583b-4f98-a4bd-b76ed41bb5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>b7b9697c-cc08-4b7f-a1c6-173a53375b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'client1-all-communications']</value>
      <webElementGuid>20a36a99-7e5b-4cea-9b2c-266249d6a9f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
