<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nature of business employment_client1_ffa724</name>
   <tag></tag>
   <elementGuidId>319daecf-4451-4f14-a46f-691965a56eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-employed-business-nature</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-employed-business-nature']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8972abc-1217-4b24-81a9-7b82114b2c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-employed-business-nature</value>
      <webElementGuid>aab727c3-8e3d-4380-8cc5-ad1a175de563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>312f2fef-4df6-4b3f-8734-9925e9efe7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>natureOfBusiness</value>
      <webElementGuid>5168bff4-13cc-482d-9062-06cc598bcbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>34d4436c-7d88-41fe-af48-7f58b150debd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>365a5e82-dc0d-452a-9adc-b23790c7cb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-employed-business-nature&quot;)</value>
      <webElementGuid>8fc1b454-8cc9-489a-b5de-5063baaf38d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-employed-business-nature']</value>
      <webElementGuid>0952431e-e29d-46ca-b936-fc2743d59d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div[4]/input</value>
      <webElementGuid>ee00a350-3a9a-4875-bbd5-787e6067f8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-employed-business-nature' and @type = 'text']</value>
      <webElementGuid>320c91ef-ca51-44d9-b2f9-2df17eee0a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
