<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_client1email</name>
   <tag></tag>
   <elementGuidId>5bb35764-f5fe-409e-8b4e-c5d90590bfdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>207593b6-2abc-4312-a9c0-38c3a6719bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>emailAddress</value>
      <webElementGuid>178c60fc-db5e-4db3-a51a-c0faa0641fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1email</value>
      <webElementGuid>aeef1a0d-d621-4207-86db-cdd8fdee8ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c3d87ebe-e4a1-4c1b-89f7-6dc7796ada75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>97a03811-2691-46fc-8217-0953ef3647a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>68cdf93e-aaff-4290-b073-372dc29a771e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$</value>
      <webElementGuid>544fca61-3d29-46a9-ae73-12d88023b39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1email&quot;)</value>
      <webElementGuid>64cfca9e-7f5d-4cc0-a2bd-2d6b6dd50cee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1email']</value>
      <webElementGuid>e5f1b0f0-bcde-4ab3-8af4-8f634b1678ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div/input</value>
      <webElementGuid>c97ca71b-ffd1-4da9-9343-5cc9971f6e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1email' and @type = 'email']</value>
      <webElementGuid>bdbe0c0a-39ac-474b-b624-13dd391e171c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
