<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__continueToReceiveIncomeInillness</name>
   <tag></tag>
   <elementGuidId>bc19745f-3f4d-4261-9ced-dd6fb2375e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continueToReceiveIncomeInillness-yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='continueToReceiveIncomeInillness-yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3824f29-2198-4518-a618-81be3fb8fae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>db74553b-c090-4571-865f-592d4dcf9335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness-yes</value>
      <webElementGuid>6e2f829d-e7f8-4aed-aa0e-835c50956b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness</value>
      <webElementGuid>b06de71e-5a12-405b-aec8-d3a6bd8193cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e83f86cc-f641-45f5-90ee-c1b1cda78a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>46516bf7-5b37-4e70-bd1c-6e65d5204344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continueToReceiveIncomeInillness</value>
      <webElementGuid>8475d510-9637-488a-997a-815c5cff38b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueToReceiveIncomeInillness-yes&quot;)</value>
      <webElementGuid>fa74df08-15a2-4353-9443-9355b7f67d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='continueToReceiveIncomeInillness-yes']</value>
      <webElementGuid>9946700c-77ef-4961-b055-fdadddd75685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div[2]/div/div/input</value>
      <webElementGuid>18e34c1a-8cb1-4c34-ae54-c9fced6d8cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'continueToReceiveIncomeInillness-yes' and @name = 'continueToReceiveIncomeInillness']</value>
      <webElementGuid>7344d7f9-7075-415e-b320-6feb0e01a53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
