<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passport_verificationIdType1</name>
   <tag></tag>
   <elementGuidId>31722cb5-e03d-4e21-8c68-62ea0c178330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-driving-licence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-driving-licence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c0f650b-c03a-4843-ba53-54f112900580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5ad65813-2252-47c0-b660-1ca0d153202e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-driving-licence</value>
      <webElementGuid>597cc90b-5c7c-4d21-a16f-34c04a0a20d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Driving licence</value>
      <webElementGuid>c8df4a8f-4d04-4d1c-817b-1b3dd7475287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>verificationIdType</value>
      <webElementGuid>12112050-938c-425f-93e6-ae59cd05b45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3cd99368-1754-476b-92c0-f5c3f66486d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9a3580c3-3b4c-4e33-bf75-0104d8a3ed77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verificationIdType1</value>
      <webElementGuid>e31ab13a-216e-4294-b2ee-ac897a98d4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-driving-licence&quot;)</value>
      <webElementGuid>f59fe92c-5db2-4071-9d6f-9a0e93f6faf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-driving-licence']</value>
      <webElementGuid>059410ff-7776-4e26-b38e-807fea0a5b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div/input[2]</value>
      <webElementGuid>53e56eab-01b5-4885-a949-62d11d00c933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-driving-licence' and @name = 'verificationIdType1']</value>
      <webElementGuid>cb2de97b-6fdf-4fec-a4c5-33308c3407fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
