<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_isPoliticallyExposedPerson1</name>
   <tag></tag>
   <elementGuidId>e101a87e-7bdb-4d92-8865-711b9f652738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-politically-exposed-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-politically-exposed-no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b718dc1-9f81-4b82-813b-2931111c05a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>01015eac-cbb1-498b-8d94-3348da1dc233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-politically-exposed-no</value>
      <webElementGuid>b08d6229-1445-4913-82a8-4b0f343f2789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isPoliticallyExposedPerson</value>
      <webElementGuid>4afb835a-be58-4cf8-a01e-f681be7f43d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b6027da9-c8d5-4fb8-9e57-499463241afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>02576c12-9529-45c1-b688-1b2a6b6554dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isPoliticallyExposedPerson1</value>
      <webElementGuid>837e3749-d60c-422f-858b-9bb2836fd0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-politically-exposed-no&quot;)</value>
      <webElementGuid>8072081b-faae-410a-8200-c9c0867edfef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-politically-exposed-no']</value>
      <webElementGuid>cdc2acc7-5cad-4c93-97bd-10d38cc744b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/input[2]</value>
      <webElementGuid>e6b2a912-6d07-4720-b63e-af8759bd8cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-politically-exposed-no' and @name = 'isPoliticallyExposedPerson1']</value>
      <webElementGuid>4a6a3a9d-5a32-4b80-9916-92e1c61a6e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
