<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year of birth_client1-financial-depen_e0587e</name>
   <tag></tag>
   <elementGuidId>8bc73920-9242-438d-ab3d-c26540c95d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-financial-dependents-yob0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-financial-dependents-yob0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e95728c-8a44-4d3a-a2b7-c058f49f7990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cded1aa8-5fdd-4f67-8e86-3f3a3b7fbd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> YYYY</value>
      <webElementGuid>253fdb35-2d4a-4792-a2f1-36cade757460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>yearOfBirth</value>
      <webElementGuid>d2ac8549-f789-47a7-9bc0-794f92736c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ec4723a6-8fd2-4d51-8906-d5176cf031cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cde9fd54-db09-409c-86bb-f352d32eae9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-financial-dependents-yob0</value>
      <webElementGuid>b0357fbb-9c7f-464e-aca8-ed8ddfe55ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9287b160-74fb-4bf1-936f-190a40b005ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-financial-dependents-yob0&quot;)</value>
      <webElementGuid>514353f8-48a2-409c-890b-35140bbd5f37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-financial-dependents-yob0']</value>
      <webElementGuid>6f43e345-4803-4766-995b-594805841ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f2a7abb8-e510-410a-970f-3a04c08b3871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = ' YYYY' and @id = 'client1-financial-dependents-yob0']</value>
      <webElementGuid>ccf3d721-97c4-41a7-9449-7c0edf7f7d47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
