<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Driving licence number_client1-drivin_e255d6</name>
   <tag></tag>
   <elementGuidId>e23b39e4-8711-4749-9075-e7a21ecbf481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-driving-passport-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-driving-passport-no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfd26e47-7c9f-40f4-9876-b41e37c45179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-driving-passport-no</value>
      <webElementGuid>6c944637-8308-4d7b-9ad6-6fc99120963a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a092d632-5500-474b-8553-961bd51d52c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>verificationIdNumber</value>
      <webElementGuid>4bdbbe09-bb4b-42a3-9174-c6488b20d480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>21d0d249-34ce-4ff1-a363-2de0d8035244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f2d4037a-526f-4f3b-8571-fd34eed9bcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-driving-passport-no&quot;)</value>
      <webElementGuid>2884a074-b6b0-48b2-966d-0a24af4232b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-driving-passport-no']</value>
      <webElementGuid>82ff52f2-99aa-4193-97e8-9d3e8ccef5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div[2]/div/input</value>
      <webElementGuid>5f3e07ce-bb32-419e-9c0c-e0f70a0e99e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-driving-passport-no' and @type = 'text']</value>
      <webElementGuid>0563d7a0-0a4a-4451-a937-c042e1696a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
