<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work telephone_client1worktelephone</name>
   <tag></tag>
   <elementGuidId>adee4981-3fb0-424d-8d69-9ebc751cf63f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1worktelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1worktelephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c73eab79-52d6-4b57-9bd7-3662fe8b0dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>workTelephone</value>
      <webElementGuid>a5588c81-7375-4304-89ac-2152cbfadc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1worktelephone</value>
      <webElementGuid>ded3afd3-8011-4c23-b041-89e4ba6f0b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83ae68d9-b47c-4c7e-b827-074331bd6e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>43dcf159-b259-4f11-ae17-c4d96cdf39b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e88982dc-df0c-425a-b9b8-988f8edc7d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1worktelephone&quot;)</value>
      <webElementGuid>a7636d19-ac95-426b-b160-b4b8fe3cbf15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1worktelephone']</value>
      <webElementGuid>3e6af294-86ef-4074-a905-cc80b7c2d839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[4]/input</value>
      <webElementGuid>5efffa64-d0a1-4010-801c-731a2a96092a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1worktelephone' and @type = 'text']</value>
      <webElementGuid>d39b249d-65db-44eb-bb0c-95b171ba55fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
