<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you have an up to date will_haveUp_45cd25</name>
   <tag></tag>
   <elementGuidId>327757af-f52d-4328-83f5-74f0be8919da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#haveUptodateWill-yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='haveUptodateWill-yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28115db5-5eae-49d7-b96f-10fb891a07c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>006207ca-1fb4-434f-bc15-75f7feecee93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>haveUptodateWill-yes</value>
      <webElementGuid>1bca2646-deac-4090-9bd8-e494494977d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>haveUptodateWill</value>
      <webElementGuid>794a781e-ad24-481f-80ed-e7d231a94b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cb89aa9f-2401-4c43-8154-7bd4e06f2ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ff112ea6-b9e3-42f0-8fd1-0748d197d517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>haveUptodateWill</value>
      <webElementGuid>a2a892ba-0ffa-4316-9834-7c90ab78c654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;haveUptodateWill-yes&quot;)</value>
      <webElementGuid>308f3110-717a-4d03-8702-b18c36fcdd61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='haveUptodateWill-yes']</value>
      <webElementGuid>bac95947-d784-4667-9930-ce012dcbe2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>b0fa065b-b38b-4e45-a232-be2475aea7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'haveUptodateWill-yes' and @name = 'haveUptodateWill']</value>
      <webElementGuid>bf54a0bd-43d3-4f91-9da4-ea06910545ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
