<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are you a member of a Defined Benefit_824ca8</name>
   <tag></tag>
   <elementGuidId>2c67bbe7-013c-40a5-b6a6-0fa89eff5f2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0ea100b-4a3f-4215-8b03-237ea1e71402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>09d5298f-25d1-4d5b-bcda-1060b65a3444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option1</value>
      <webElementGuid>7617145a-0287-4cc2-8034-5a2bbb79323a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalaryScheme</value>
      <webElementGuid>3634eee9-9a86-449d-9dd4-111288f6b2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e93f3d34-c590-4761-98da-bdefa24a57e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2e524703-2730-43b1-bc05-52fc041692a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isMemberOfDefinedBenefitsOrFinalSalaryScheme1</value>
      <webElementGuid>fb2c5ee9-13fb-4323-ac69-542619bee017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option1&quot;)</value>
      <webElementGuid>ef6dfaa6-693b-4b4d-ac5c-f8f7daf96ebc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option1']</value>
      <webElementGuid>d7247a74-8d14-48ac-9a2c-585baeae1fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/input</value>
      <webElementGuid>a88bfc00-ff5a-4df5-be30-1db51305ecb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'isMemberOfDefinedBenefitsOrFinalSalarySchemeClient1Option1' and @name = 'isMemberOfDefinedBenefitsOrFinalSalaryScheme1']</value>
      <webElementGuid>f221aa87-821d-455e-a55e-d70fab174955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
