<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I take risks at every opportunity_ris_ad1f78</name>
   <tag></tag>
   <elementGuidId>c2c566a9-6d48-4ed7-aaa7-9a1d362df3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#riskQuestionsClient134Answer144</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='riskQuestionsClient134Answer144']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c416781-795a-41d1-97f7-7123a868fceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>717e4ac7-8964-44dd-a34b-b9c6539fa114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e8e49c79-6f64-4abc-b8ef-55e9d2cc0b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>riskQuestionsClient134Answer144</value>
      <webElementGuid>19fa4bcf-7d00-41d6-ace6-85c634da04c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>65bb8340-a672-4646-ba58-c77c13892b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riskQuestionsClient134Answer144&quot;)</value>
      <webElementGuid>0a4439c8-32d6-42c6-91cf-9de5c7607734</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='riskQuestionsClient134Answer144']</value>
      <webElementGuid>78249f7c-677b-45b7-93b0-d2f5d1914da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/input</value>
      <webElementGuid>03e94289-7739-4c5c-a532-c20a48d6b3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'riskQuestionsClient134Answer144']</value>
      <webElementGuid>5a46cb29-9378-4e34-bbd6-2115320f9697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
