<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To achieve financial success, I would_75bff1</name>
   <tag></tag>
   <elementGuidId>b8b67cb5-7b33-491f-ab92-9282d4e8e229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#riskQuestionsClient120Answer73</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='riskQuestionsClient120Answer73']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc6bfc58-dbdf-4f09-a196-30bde715b0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ca1964ed-f152-4a51-9177-899da83157e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e1d98d78-3da8-4f7b-81b7-1bc37c506ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>riskQuestionsClient120Answer73</value>
      <webElementGuid>4d0ad529-56f8-4c97-8370-4928b51395a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a57cfdd7-ebfa-4b1d-aa42-c77a85cc3cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riskQuestionsClient120Answer73&quot;)</value>
      <webElementGuid>5454c826-e5c7-4b4a-8333-2973d81e95f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='riskQuestionsClient120Answer73']</value>
      <webElementGuid>25a4a33e-8e9b-4a2b-a370-2669e414a259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dynamic-questionnaire/div/div/div/input</value>
      <webElementGuid>46ef6d2b-75b8-442c-9516-372ddaf39683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'riskQuestionsClient120Answer73']</value>
      <webElementGuid>1c84a7af-22ed-409f-ad84-781485aa538a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
