<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How would you describe your health_he_9bfa41</name>
   <tag></tag>
   <elementGuidId>d6d53ee3-16d2-42da-a862-bf80946bf457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-health-good</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-health-good']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0466b77b-d49d-46db-9fab-7611d34d05d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0e1efdcf-07a2-43b7-834e-3dbc2d1c5068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-health-good</value>
      <webElementGuid>3442198e-9d62-433e-a799-9a665330d67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>healthCondition</value>
      <webElementGuid>51dcb78b-d339-423a-b3fe-dbd67277e930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c77c9559-77e6-4316-8105-b0b9d34ef0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>97b3db78-455f-45a8-b44b-c47eb2b42b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>healthCondition1</value>
      <webElementGuid>15c0b848-6f67-488b-9885-f05deec68f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-create-application[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-l&quot;]/div[@class=&quot;col-12 mt-xl mb-xxl&quot;]/app-tabs[1]/div[@class=&quot;tabs--container row&quot;]/div[@class=&quot;tabs--body col-12&quot;]/app-tab[8]/div[1]/app-five-point-health-check[1]/div[@class=&quot;container p-0 bg-white box-shadow-grey&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/section[@class=&quot;row pl-l pt-m pb-m&quot;]/div[@class=&quot;col-5&quot;]/div[@class=&quot;form-group ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-checkbox&quot;]/input[@id=&quot;client1-health-good&quot;]</value>
      <webElementGuid>17968248-420b-41d8-8fc9-aae61f11a9fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-health-good']</value>
      <webElementGuid>58fbc5f8-cda7-472c-9108-37c9ae25a5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/input</value>
      <webElementGuid>d229edb7-37b8-4313-9c76-495aaf33be37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-health-good' and @name = 'healthCondition1']</value>
      <webElementGuid>148bff32-1314-42d4-84c3-fce169f7f41b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
