<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OccupationJob title_client1-employed-_f9375d</name>
   <tag></tag>
   <elementGuidId>c6579d72-61e1-4d91-a8e8-da60b3503540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-employed-occupation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-employed-occupation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fb66aeb-5f85-421f-bf30-a03d86699f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-employed-occupation</value>
      <webElementGuid>a6bcf782-81a4-4708-8e88-124e659b4e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90fab2ce-06d6-43d7-9a67-ec0dea6003e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>occupation</value>
      <webElementGuid>6df7ca66-f2a9-415f-b4a9-29ffe4c0e194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4d3d0e56-e5c0-4f03-b422-f52ce3be27dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a58cd47c-ae8a-457f-aaf5-7a619dd752e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-employed-occupation&quot;)</value>
      <webElementGuid>eadc40a2-9f35-404f-b02b-b5d4a4876e1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-employed-occupation']</value>
      <webElementGuid>48748ad9-48f7-4546-898e-2a2cd0d7f0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div[2]/input</value>
      <webElementGuid>c37a9d6e-14b3-4d69-926e-81b0241ce52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-employed-occupation' and @type = 'text']</value>
      <webElementGuid>14af8d04-7194-4e33-8838-949c2c21f134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
