<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Home telephone_client1hometelephone</name>
   <tag></tag>
   <elementGuidId>3280d2a1-5815-468b-b4c3-1c8fb5809a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1hometelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1hometelephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7245b5c-0afb-4d08-978d-f5fecf327f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>homeTelephone</value>
      <webElementGuid>ec00b069-ad4f-44c5-b035-a18fb47fd371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1hometelephone</value>
      <webElementGuid>9dfb21d2-b7b6-484b-896d-f6125ad99b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7acbb37-a1d3-456c-b2b7-06fe7f1755ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0d3868c7-7bc2-43f8-9525-c7e091488304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>32df9989-ae87-4690-b3c0-3e8200b2cfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1hometelephone&quot;)</value>
      <webElementGuid>fc74f8e7-a305-4d75-8f0c-83ccc0d031bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1hometelephone']</value>
      <webElementGuid>1059ed3f-9ff2-4db0-b575-a6cfe28eef74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[2]/input</value>
      <webElementGuid>e088408b-ace4-4a0e-a91c-ab256b68cebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1hometelephone' and @type = 'text']</value>
      <webElementGuid>f503c311-95ee-4eef-9577-e310bcb4a605</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
