<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passport_verificationIdType1</name>
   <tag></tag>
   <elementGuidId>31722cb5-e03d-4e21-8c68-62ea0c178330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-driving-licence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-driving-licence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72656f23-6c60-4c2c-9255-955d215b8601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5704da33-0a07-4c1f-8883-11e71f9c6c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-driving-licence</value>
      <webElementGuid>81de2aa8-0064-4495-8b37-6700439b70bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Driving licence</value>
      <webElementGuid>935d9daa-5442-4975-a7da-47fd2b30072f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>verificationIdType</value>
      <webElementGuid>f9becefa-4788-4e8a-81ce-3e36679d5f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>859a92e9-7a5c-483a-be0d-13a0887d959d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c6046c70-89a6-4f46-b372-a2dccdfd866a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verificationIdType1</value>
      <webElementGuid>f558820e-86d7-48ac-8746-9e04caf59eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-driving-licence&quot;)</value>
      <webElementGuid>69ca2b32-18fd-4347-92db-3b2cc9753a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-driving-licence']</value>
      <webElementGuid>48eb0938-97d5-4995-92b6-046bf2fe1a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div/input[2]</value>
      <webElementGuid>551ea90e-0e29-49fa-9df0-f09246371df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-driving-licence' and @name = 'verificationIdType1']</value>
      <webElementGuid>e768b6e7-92c4-4e88-8bbe-9d6125e162e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
