<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Communication and Marketing Preferenc_8fce92</name>
   <tag></tag>
   <elementGuidId>7ef02bc7-26f9-4119-b109-bece91365389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-contact-post</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-contact-post']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>538e3cc1-6297-46a2-85a3-2d73e64b12b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isContactableViaPost</value>
      <webElementGuid>63bb2138-c0d2-4feb-a9e0-ccf7d5dd8269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3dbbc044-3b66-4aa5-8b49-cf6b8ba06b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-contact-post</value>
      <webElementGuid>45e01e6d-56db-44c5-9f43-1c06cc57e38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>902aa994-7bc5-44b3-afff-19d866baa924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>99053ff1-cc39-480c-a1bf-69db90fc16de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-contact-post&quot;)</value>
      <webElementGuid>2bf85bfa-e874-466d-8bd3-2e2547224922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-contact-post']</value>
      <webElementGuid>2cb788c6-ff35-45d9-b8a3-eda9e9878b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>144a30b1-b126-4016-8227-589e0d13b9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'client1-contact-post']</value>
      <webElementGuid>4987682a-ea98-482f-9f4b-05a40947eeeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
