<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_UnpublishedPublishSigned off_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>6f0059e9-1d9c-4395-aca0-1cffe48bebef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-select.ng-valid.ng-star-inserted.ng-dirty.ng-touched</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='publish-settings-overlay']/app-publish-settings/div/div/div[2]/div/div/div[3]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1a67fc9d-c8da-4d24-b9b1-fd979ab090e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clientDetailsStatus</value>
      <webElementGuid>c77421ec-be96-46e0-b913-11494cc05d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-valid ng-star-inserted ng-dirty ng-touched</value>
      <webElementGuid>c7f7b476-7d21-4d87-8337-1f0705fdd056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>305401a3-9b22-497a-8ce5-0f2e745c09fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UnpublishedPublishSigned off</value>
      <webElementGuid>e333ec7d-33bd-426b-b3e5-b75ee57504b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publish-settings-overlay&quot;)/app-publish-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;bg-white&quot;]/div[@class=&quot;container pt-xl pb-xl mb-xxl&quot;]/div[@class=&quot;flex-grid flex-grid--2&quot;]/div[@class=&quot;flex-grid__cell ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;row alternate-table-rows&quot;]/div[@class=&quot;row col-12&quot;]/div[@class=&quot;col-5 p-xs pr-l&quot;]/select[@class=&quot;form-select ng-valid ng-star-inserted ng-dirty ng-touched&quot;]</value>
      <webElementGuid>86fc5d03-9fed-4a91-bcb4-4e5c25af47c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='publish-settings-overlay']/app-publish-settings/div/div/div[2]/div/div/div[3]/div[2]/select</value>
      <webElementGuid>2384b8f7-ecb6-46d4-be73-3d3a58350311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client details'])[2]/following::select[1]</value>
      <webElementGuid>57d5ecc9-248c-48cb-9615-2de47f317875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>a709f711-43de-4157-a378-cfd5cf0ddee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional details'])[1]/preceding::select[1]</value>
      <webElementGuid>93f51f4e-0c15-4d2a-b002-16808f568f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial details'])[2]/preceding::select[2]</value>
      <webElementGuid>84a405ef-2779-4f7f-8a52-e15412b685d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>a7e09558-09ff-44ba-81dd-2e4f3ff59515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'UnpublishedPublishSigned off' or . = 'UnpublishedPublishSigned off')]</value>
      <webElementGuid>cfac8c4b-3165-4034-8ce4-489c1c49afe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
