<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select NationalityBritishAfghaniAlba_eb0c08</name>
   <tag></tag>
   <elementGuidId>23e1f146-ba6e-4a0b-a283-0981ce8d9565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-nat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client1-nat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1e28cb1b-bb4a-47ae-a422-cdae5b9532d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-nat</value>
      <webElementGuid>802a79cd-ac3b-4e1a-b679-9c50de4c8649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nationality</value>
      <webElementGuid>38e77f2f-7a8e-4fc9-accc-82ddbc0cffb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a0233bc4-c0f6-4814-a76b-a4f4fae923f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6f690245-787a-44ff-a947-dedfb0f00a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean</value>
      <webElementGuid>4580e338-6279-4aa1-b320-cc760dda700a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-nat&quot;)</value>
      <webElementGuid>196ca472-c3f9-49ed-8912-d824b83a2e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1-nat']</value>
      <webElementGuid>adacb288-d24c-4c38-ad9a-88a6444083a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/following::select[1]</value>
      <webElementGuid>97db77ae-e2b3-4b9d-a7d4-b1a3f6326502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality/ Personal Identifier/s'])[1]/following::select[1]</value>
      <webElementGuid>d2a417a8-0ed4-4e79-9446-40fb946b59eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax residency'])[1]/preceding::select[1]</value>
      <webElementGuid>35de54eb-2b69-4baf-a082-2d146a001178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First country of tax residency'])[1]/preceding::select[1]</value>
      <webElementGuid>091d2c7b-e1cf-4bdc-918b-51e8b0322732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/select</value>
      <webElementGuid>f989c834-389d-484b-85e2-2335cddafe5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1-nat' and (text() = 'Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean' or . = 'Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean')]</value>
      <webElementGuid>f3f8bba4-84f8-4570-8f5c-cb04fe8aca14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
