<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select titleMrMsMrsMissDrOther</name>
   <tag></tag>
   <elementGuidId>559f0baf-2aa9-41f9-98c6-ddcafa95eecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client1title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>94d2cd93-a719-451f-821f-d9d41ff3315c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>b3058fa2-6a81-45cb-b6bb-efa8567e74b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1title</value>
      <webElementGuid>7e1e7cef-b37b-482b-8aa7-d93ed3e1d95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2451abb8-f396-431d-a106-f69b2d14c997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8e34328f-66bd-4116-b70b-3cbdeb768d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select titleMrMsMrsMissDrOther</value>
      <webElementGuid>2af7a3cd-f1f7-4eb2-94ca-a32108d1751b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1title&quot;)</value>
      <webElementGuid>7297f453-29e9-4c36-b8cb-8c9b1c6eb593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1title']</value>
      <webElementGuid>57f524fb-f9b6-4bd9-9f50-8d895bbf6c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title*'])[1]/following::select[1]</value>
      <webElementGuid>f239750b-e5b1-41a5-baed-fdf4a421fa88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal information'])[1]/following::select[1]</value>
      <webElementGuid>712cac1a-e03e-493a-93b8-87b7f3e97411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name/s*'])[1]/preceding::select[1]</value>
      <webElementGuid>b8ff2d54-d787-416a-8249-f2f60eef1a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name*'])[1]/preceding::select[1]</value>
      <webElementGuid>3af7b4ed-a9ea-4f9b-ad3d-f9fd5cc4cf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/select</value>
      <webElementGuid>076ca9c5-e97d-450d-889a-473b51a51d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1title' and (text() = 'Select titleMrMsMrsMissDrOther' or . = 'Select titleMrMsMrsMissDrOther')]</value>
      <webElementGuid>310b8d99-76d9-4a1a-8eeb-3e5d5bea8fd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
