<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_UnpublishedPublishSigned off_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>91496c54-0835-45f8-a323-e7f2b8e97268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.col-12.ng-star-inserted > div.col-5.p-xs.pr-l > select.form-select.ng-valid.ng-star-inserted.ng-dirty.ng-touched</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='publish-settings-overlay']/app-publish-settings/div/div/div[2]/div/div/div[6]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>195871ba-0f3b-4bbd-bf2b-f0af1639b8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>riskQuestionsStatus</value>
      <webElementGuid>84c2cef8-5750-46fe-bc4a-3b5898dd8dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-valid ng-star-inserted ng-dirty ng-touched</value>
      <webElementGuid>5d791cbd-6dd7-4274-b8ce-3c56285fd679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>92a78bdc-1254-4119-99c9-e0dce34e1f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UnpublishedPublishSigned off</value>
      <webElementGuid>918baf21-6a12-42de-9a91-bbbd076cde7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publish-settings-overlay&quot;)/app-publish-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;bg-white&quot;]/div[@class=&quot;container pt-xl pb-xl mb-xxl&quot;]/div[@class=&quot;flex-grid flex-grid--2&quot;]/div[@class=&quot;flex-grid__cell ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;row alternate-table-rows&quot;]/div[@class=&quot;row col-12 ng-star-inserted&quot;]/div[@class=&quot;col-5 p-xs pr-l&quot;]/select[@class=&quot;form-select ng-valid ng-star-inserted ng-dirty ng-touched&quot;]</value>
      <webElementGuid>c814a54f-0d3b-4c16-adfb-c7fab9c16a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='publish-settings-overlay']/app-publish-settings/div/div/div[2]/div/div/div[6]/div[2]/select</value>
      <webElementGuid>3f218e33-1c51-4938-998b-995889030608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Risk questions'])[1]/following::select[1]</value>
      <webElementGuid>c0b6aa42-a45e-44b3-a5e8-061c54586385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial details'])[2]/following::select[2]</value>
      <webElementGuid>4a190d0c-c86f-4a1d-9b86-1e3e54a333b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Five Point Health Check'])[2]/preceding::select[1]</value>
      <webElementGuid>71c32a1a-08cf-4ce2-aee1-996280ceca6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Declarations'])[1]/preceding::select[2]</value>
      <webElementGuid>a1c12b87-30f6-4bca-bd3c-30ac06a40775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/select</value>
      <webElementGuid>c3c9755a-6616-4d99-a796-e45b87d988c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'UnpublishedPublishSigned off' or . = 'UnpublishedPublishSigned off')]</value>
      <webElementGuid>8d3964c7-a8bd-484c-b56b-0bab73fa170c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
