<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectSpouseEx-spouseChildRel_684a2e</name>
   <tag></tag>
   <elementGuidId>766ef5b6-e60d-462f-94ab-5ce33f103949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-financial-dependents-relationship0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client1-financial-dependents-relationship0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>92bbe6f2-37e3-4839-8630-4b81fe2c125c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>relationship</value>
      <webElementGuid>79f1d0f3-7f0c-495e-836d-b56678e70f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>901a7029-529c-42ab-aee8-2e1f89a6527f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-financial-dependents-relationship0</value>
      <webElementGuid>8a7238c8-a2dd-4850-88fe-949aaa94a991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bece9a35-ce2f-4119-b893-a940e26a13a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectSpouseEx-spouseChildRelativeFriend</value>
      <webElementGuid>7b0d08d0-4c28-40a9-a84b-092ee970dd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-financial-dependents-relationship0&quot;)</value>
      <webElementGuid>bfdd56bf-f939-49a4-b517-a5416c70af96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1-financial-dependents-relationship0']</value>
      <webElementGuid>cc54613d-1824-4704-a16e-31e478524fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship'])[1]/following::select[1]</value>
      <webElementGuid>c633dc58-3a9f-4831-97fd-6a603674b73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::select[1]</value>
      <webElementGuid>c761a4aa-8712-48c6-bcc7-cd2980572049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year of birth'])[1]/preceding::select[1]</value>
      <webElementGuid>f4385979-72be-49af-9738-90f8774907d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add additional dependents'])[1]/preceding::select[1]</value>
      <webElementGuid>59c0e7b4-2c5d-4245-8e8d-163b4c92e257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>2e3e931d-cd71-4f59-9640-68a2ef13643c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1-financial-dependents-relationship0' and (text() = 'Please selectSpouseEx-spouseChildRelativeFriend' or . = 'Please selectSpouseEx-spouseChildRelativeFriend')]</value>
      <webElementGuid>5cb15eac-736b-496c-a9ef-53bcee50319a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
