<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select NationalityBritishAfghaniAlba_eb0c08</name>
   <tag></tag>
   <elementGuidId>23e1f146-ba6e-4a0b-a283-0981ce8d9565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-nat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client1-nat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fe972c32-46f3-40a1-964e-8220169c60a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-nat</value>
      <webElementGuid>f1b7b16f-f737-49f9-8d6d-9b620e27d023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nationality</value>
      <webElementGuid>879d0764-7509-467a-9da4-dd845f9d2a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4b36620c-22fc-44ba-9228-5e9b4e9b4433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0f790cb4-ef81-4d05-b16a-047bdf8ca387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean</value>
      <webElementGuid>05fda6e4-761f-460a-b83b-09791e6e6ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-nat&quot;)</value>
      <webElementGuid>f6c886e6-0e85-4735-b619-90c68442b06f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1-nat']</value>
      <webElementGuid>0a7b639e-0a94-4bf7-becd-f3ffc8b46ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/following::select[1]</value>
      <webElementGuid>240c1cd4-dc7a-4432-b3ab-efaf1d31a268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality/ Personal Identifier/s'])[1]/following::select[1]</value>
      <webElementGuid>14becbe9-fb55-4bc3-ac04-f3ce14983c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax residency'])[1]/preceding::select[1]</value>
      <webElementGuid>3fa92b4f-c91e-4b28-a873-1502b35c4d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First country of tax residency'])[1]/preceding::select[1]</value>
      <webElementGuid>5f9a54a2-2b3c-4e2f-9cb5-22674eafe93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/select</value>
      <webElementGuid>aa625ee6-b012-4b56-8036-730d3b4733c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1-nat' and (text() = 'Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean' or . = 'Select NationalityBritishAfghaniAlbanianAlgerianAmericanAmerican (Minor Outlying Islands)American SamoanAndorranAngolanAnguillanAntarcticanAntiguans/BarbudansArgentineanArmenianArubanAustralianAustralian (Heard Island and Mcdonald Islands)AustrianAzerbaijaniBahamian BahrainiBajianBangladeshiBelarusianBelgianBelizeanBenineseBermudanBhutaneseBolivianBonaire, Saint Eustatius and SabaBosnianBouvet IslanderBrazilianBritish (Indian Ocean Territory)British (Saint Helena, Ascension and Tristan Da Cuna)British (Virgin Islands)BruneianBulgarianBurkinabeBurmeseBurundianCambodianCameroonianCanadianCape VerdeanCaymanianCcocs IslanderCentral AfricanChadianChileanChineseChristmas IslandersColombianComoriansCongoleseCongoleseCook IslandersCosta RicanCroatian CubanCuracaoCypriotCzechDanishDjiboutiDominicanDominican (Dominica)DutchDutch (Saint Martin)Dutch AntilleanEast TimoreseEcuadoreanEgyptianEmiratiEquatoguineanEritreanEstonianEthiopianFalkland IslanderFaroe IslandersFijianFinishFrenchFrench (Saint Barthelemy)French (Saint Martin)French (Saint Pierre and Miquelon)French (southern Territories)French GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarianGreekGreenlandersGrenadian GuadeloupianGuamanianGuatemalanGuernseymen Guinea-BissauanGuineanGuyaneseHaitianHonduranHong Kong ChineseHungarianIcelandicI-KiribatiIndianIndonesianIranianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJersey IslanderJordanianKazakhstaniKenyanKittitian/NevisianKoreanKuwaitiKyrgyz LaotianLatvianLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourgersMacao ChineseMacedonianMahoranMalagasyMalawianMalaysianMaldivianMalianMalteseManxMarshalleseMartiniquaisMauritanianMauritianMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMosothoMotswanaMozambicanNamibianNauruanNepaleseNew CaledonianNew ZealanderNicaraguanNigerianNigerienNiueanNi-VanuatuNorfolk IslanderNorth KoreanNorthern Mariana IslanderNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New GuineanParaguayanPeruvianPhillipinoPitcairn IslandersPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint LucianSaint VincentianSalvadoranSammarineseSamoanSao Tome and Principe IslandersSaudi ArabianSenegaleseSerbian SeychelloisSierra LeoneanSingaporeanSlovakian Slovenian Solomon IslanderSomaliSouth AfricanSouth Georgia and South Sandwich IslandersSpanishSri LankanSudaneseSurinamese Svalbard and Jan Mayen IslandersSwaziSwedishSwissSyrianTaiwaneseTajikTanzanianThaiTogoleseTokelauansTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslanderTuvaluanUgandanUkrainianUruguayanUS Virgin IslanderUzbekVatican CityVenezuelanVietnameseWallis and Futuna IslandersWestern SaharanYemeni ZambianZimbabwean')]</value>
      <webElementGuid>2b18b812-135c-48dc-8f32-8a26e4063b97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
