<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Education details_client1-qualific_f35bc7</name>
   <tag></tag>
   <elementGuidId>81e91bce-aa4e-40c5-96d8-dffa21ef0949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client1-qualifications-details</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='client1-qualifications-details']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>19729a6e-88fd-4c26-98f2-8cd202f5b714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-qualifications-details</value>
      <webElementGuid>0b065110-7af7-4087-b016-a7fe6d3bc43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>qualificationsDetails</value>
      <webElementGuid>b0ae3bc1-8ce2-4b8a-abac-70c614529494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>1ab3bcc6-48d8-4c52-acf7-399ec01298c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e37c8ad-bda8-4264-afc9-454405ec475a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-qualifications-details&quot;)</value>
      <webElementGuid>15105e02-74ef-4192-a31e-40e280733798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='client1-qualifications-details']</value>
      <webElementGuid>0129514a-04d9-45d3-8e04-937cdba9cb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>3d918ac2-afbc-493f-b66b-8cad7d27eb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'client1-qualifications-details']</value>
      <webElementGuid>eaff85c9-1de8-4370-b88b-dafe44fe6dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
