<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Password</name>
   <tag></tag>
   <elementGuidId>d2f07e2c-14c1-43af-aa8e-9eea98f63e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Password' or . = 'Password')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Password' or . = 'Password')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bf5cd314-e4db-4c00-aee5-e18f5d03bec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>02e9773c-a4a9-43e0-942c-ae470373e455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>82f9ba11-089d-4848-8441-7d5c75d9df4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>2cd2cbc0-96ce-4e98-ae79-18ac57bfc447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-signin[1]/lib-kaleidoscope-kate[1]/lib-signin[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;container mt-xxl mb-xxl&quot;]/div[@class=&quot;row column-gap__dynamic&quot;]/div[@class=&quot;bg-white col-8 col-mobile-12 p-mobile-l p-xxl box-shadow-grey br-xs&quot;]/div[@class=&quot;row mb-l column-gap__dynamic&quot;]/div[@class=&quot;col-8 col-tablet-12&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;form-label&quot;]</value>
      <webElementGuid>d2472af6-0f7f-4e96-acd8-a46bf3af460c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Password' or . = 'Password')]</value>
      <webElementGuid>0f8efbba-5db0-47cb-944a-10327a28aed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::label[1]</value>
      <webElementGuid>967f38f7-259c-4f39-8e1a-6129e00eaf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::label[2]</value>
      <webElementGuid>968b5deb-3bb4-4f08-a01e-efbdce275a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten your details?'])[1]/preceding::label[1]</value>
      <webElementGuid>7ce2789c-837a-4ffe-b937-3fccc863c25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::label[1]</value>
      <webElementGuid>7a56222e-7c67-4e5c-8639-9300fdb694ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password']/parent::*</value>
      <webElementGuid>a8aaff64-9c7c-480b-a0c8-9669e3c6e968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>f6c4f8f8-7db8-4c51-b869-a7d0757ec0da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
