<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No_isRetirementDateFlexible</name>
   <tag></tag>
   <elementGuidId>2e2df066-8959-46cf-bbe3-a75a614cc3cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retirement-date-flexible-unsure']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#retirement-date-flexible-unsure</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e010076-e526-463c-9837-3be81b046952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8a9a401d-1643-4c6a-97f7-94001c6f2627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retirement-date-flexible-unsure</value>
      <webElementGuid>7154f241-e5c6-441e-a96d-731a56bc4742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isRetirementDateFlexible</value>
      <webElementGuid>fb48a379-2485-40a3-9e39-ab2403f2ece7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-dirty ng-valid ng-touched</value>
      <webElementGuid>0c37363e-7645-4043-8b08-76775d4a4620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a3fb1041-f9f7-47a4-ac54-891b297db13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isRetirementDateFlexible</value>
      <webElementGuid>b4654d74-f4c5-406d-bab9-72d39b5ff455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retirement-date-flexible-unsure&quot;)</value>
      <webElementGuid>b29c4725-5adc-432b-ac34-43006f92b4c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retirement-date-flexible-unsure']</value>
      <webElementGuid>73732f70-56b7-4dca-86c5-834f97eb9afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tab[11]/div/app-retirement-planning-details/div[2]/form/fieldset/div/div[2]/div/div/input[3]</value>
      <webElementGuid>575a2ca0-54e6-403a-a066-d98e39da8308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'retirement-date-flexible-unsure' and @name = 'isRetirementDateFlexible']</value>
      <webElementGuid>95dd4f9b-fc9f-4e62-ad83-016c8d227d31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
