<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_isOtherFinancialInformationAvailable1</name>
   <tag></tag>
   <elementGuidId>b779503d-142e-4738-b070-ca05c2d9eb2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherInformationClient1Option2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherInformationClient1Option2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eeeb274e-1859-4623-84da-7e88bd4197de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bdf850ca-1055-460c-b671-037c100f475b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherInformationClient1Option2</value>
      <webElementGuid>2c228ff8-d46d-4ff2-bf9d-f7e3e9109b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isOtherFinancialInformationAvailable</value>
      <webElementGuid>9d6bfcb3-107c-4123-94f1-6a91306277d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b589c883-b5fd-4ddf-9dec-5a8dc5c8b713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6533f4d7-5dc8-45f4-92ec-8717a55f3b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isOtherFinancialInformationAvailable1</value>
      <webElementGuid>098e3c8c-994b-48f7-8008-af122e3149c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherInformationClient1Option2&quot;)</value>
      <webElementGuid>2b45b6de-ac6e-4edf-a503-bc39111769e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherInformationClient1Option2']</value>
      <webElementGuid>f5a9d300-0770-41d7-aef2-559b8cd1c887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>38f3c304-77be-463d-84b8-861b5fc86f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'otherInformationClient1Option2' and @name = 'isOtherFinancialInformationAvailable1']</value>
      <webElementGuid>55b6d161-3f64-49d3-b4b1-4b3a18f64879</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
