<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_willNetAnnualIncomeChangeInNext12Months1</name>
   <tag></tag>
   <elementGuidId>03292d88-4436-4d57-b8a3-f715ee0fb369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='incomeChangeClient1Option2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#incomeChangeClient1Option2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb0c068f-9b54-4ab1-9ee7-7d1620f8b99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8fc26b61-8d63-4461-95a7-77e17162f9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incomeChangeClient1Option2</value>
      <webElementGuid>ee1ac8bb-0761-4996-8a7d-57066e44e89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>willNetAnnualIncomeChangeInNext12Months</value>
      <webElementGuid>24f4a20f-c041-482c-830b-e0c437ae8b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a4f0f608-d130-47ce-b1e4-76ff80edfdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>522f104e-1fc1-4d7a-9cb9-3ce35fae6545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>willNetAnnualIncomeChangeInNext12Months1</value>
      <webElementGuid>fc002632-498c-4639-8d76-59208cfab171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incomeChangeClient1Option2&quot;)</value>
      <webElementGuid>e2aeca4c-257f-450f-a60a-205d7efcaeeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='incomeChangeClient1Option2']</value>
      <webElementGuid>440adf2b-dd63-4d25-9889-11d74204fef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>a2b2b16a-2df7-48f5-af40-afe3e4d56e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'incomeChangeClient1Option2' and @name = 'willNetAnnualIncomeChangeInNext12Months1']</value>
      <webElementGuid>84f0fe4a-b47c-448d-88c0-ca2e948dd201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
