<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unsure_retirementplanning-client2-pen_0ea17e_1</name>
   <tag></tag>
   <elementGuidId>8273d5e6-364e-4c83-b39e-1bc1c1f8399a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retirementplanning-client2-pension2LastContributedYear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#retirementplanning-client2-pension2LastContributedYear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22edc7ec-0267-42e7-aac4-ef4970fe27dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1d406ca-c344-4f22-ad77-8d093695059f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> YYYY</value>
      <webElementGuid>c4079f0b-64ce-4b05-bc77-500b12381388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>pension Last contributed year</value>
      <webElementGuid>bb377a87-3f05-4146-a65e-bebe4646053a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>lastContributedYear</value>
      <webElementGuid>50b6f209-1a4e-4400-9068-2f2d13e88d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>13166d86-dbf2-4acd-bfb2-d262ede6a19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9fcb22a2-dcc4-43ad-a7d8-8007d186ec95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retirementplanning-client2-pension2LastContributedYear</value>
      <webElementGuid>6ff633f5-18b2-4eff-93ea-f51b54daf982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f305b53d-38d7-4933-a56f-d24fa7f5dbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retirementplanning-client2-pension2LastContributedYear&quot;)</value>
      <webElementGuid>1a66a567-bfb1-4b2c-be37-1f95da637e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retirementplanning-client2-pension2LastContributedYear']</value>
      <webElementGuid>9376d505-d515-4bbd-a85d-821c3176416c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div[2]/input</value>
      <webElementGuid>ec94f7c0-cfdc-476d-988f-c8aa81601c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = ' YYYY' and @id = 'retirementplanning-client2-pension2LastContributedYear']</value>
      <webElementGuid>375dd0ba-7a39-48f8-84b3-5c5be90ab5ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
