<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_willNetAnnualIncomeChangeInNext12Months1 (1)</name>
   <tag></tag>
   <elementGuidId>148a9a77-8b6a-45c4-8b81-87666ed1818f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='incomeChangeClient1Option2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#incomeChangeClient1Option2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7eab5df-1903-46da-b4e2-feb73dcd161a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e666d87c-ca24-46f0-bfa4-1db4f63b9980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incomeChangeClient1Option2</value>
      <webElementGuid>f541e0e2-ad84-41b9-8c43-309026cadde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>willNetAnnualIncomeChangeInNext12Months</value>
      <webElementGuid>4304e5f8-b241-42e2-baa5-cfba60c0f1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d1a03bd9-138d-43b0-9609-f27063ccbc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>12cfea5f-53af-440e-a8bf-2370fbcfc01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>willNetAnnualIncomeChangeInNext12Months1</value>
      <webElementGuid>bddf1847-8794-4d5f-8a91-d1d480dcec36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incomeChangeClient1Option2&quot;)</value>
      <webElementGuid>607669a8-508f-4a77-8450-fbcc6a051b26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='incomeChangeClient1Option2']</value>
      <webElementGuid>914a0ab3-a450-4b1d-89fe-368bd74c848f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>8bdee602-794f-43a8-8393-08eb6ba5e4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'incomeChangeClient1Option2' and @name = 'willNetAnnualIncomeChangeInNext12Months1']</value>
      <webElementGuid>99dce6f2-c2ce-4356-a4e5-86c1a0c7fc2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
