<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_gender1</name>
   <tag></tag>
   <elementGuidId>71f97854-b7c4-4fb6-914f-b5c229241a85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1gendermale']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1gendermale</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ac99513-1a63-4def-be28-7e401a84d068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a0314d6d-bae0-4474-ba7c-c2f719465575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1gendermale</value>
      <webElementGuid>575fdc7d-0587-4d95-b6c0-a7974446f624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>male</value>
      <webElementGuid>5359609c-ac8c-454d-9006-a013e2ed3627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>dcf8a260-7bb2-4b77-9a51-4d5652b9ce22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e3d7ee1c-704c-47a8-ac6b-d1a4ea7bf78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9a628d4-6ad5-400f-97cf-1cbfc102cedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender1</value>
      <webElementGuid>25be4ee9-414d-46c6-99de-6533887242fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1gendermale&quot;)</value>
      <webElementGuid>8f085dfd-8dd0-4eb4-a6cd-d76aa8e0f6b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1gendermale']</value>
      <webElementGuid>df77d09d-e02e-4582-bbc2-0ad012544eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>12bd6b73-e571-43a8-8f2d-d9833e9d6e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1gendermale' and @name = 'gender1']</value>
      <webElementGuid>949fd1dd-11f2-4a02-b4b9-a5c854cede46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
