<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Disagree_riskQuestionsClient128Answer115 (1)</name>
   <tag></tag>
   <elementGuidId>ea4f34bc-3bf4-40cb-9333-6409479ad65e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='riskQuestionsClient128Answer115']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#riskQuestionsClient128Answer115</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67c672c3-edb5-4d10-8f95-1a005e9e69c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6c2d0474-9a37-4ece-a263-24ce13d8d010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1f7cb520-07f7-43af-8d77-56d70556bde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>riskQuestionsClient128Answer115</value>
      <webElementGuid>5c24f808-46d7-4e3d-9ed0-266ec22aaa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>01796c93-4b77-4db9-957c-1a04cb7cfc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riskQuestionsClient128Answer115&quot;)</value>
      <webElementGuid>97af6198-0847-4a53-9281-de5348a04e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='riskQuestionsClient128Answer115']</value>
      <webElementGuid>2fe384e1-2565-4b7b-b474-f7ee1f46aaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dynamic-questionnaire/div/div[9]/div[3]/input</value>
      <webElementGuid>f09b80c8-4744-4812-8564-1311b6be7e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'riskQuestionsClient128Answer115']</value>
      <webElementGuid>738476da-f3b4-4eb5-b67b-234a09ad517b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
