<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expected retirement age_client1-emplo_dac0ea</name>
   <tag></tag>
   <elementGuidId>bd4825eb-7978-4962-b1bd-5b5efbccc2ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-employed-retirement-age']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1-employed-retirement-age</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6ab7d84-da3b-4160-9a80-a074469e235d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-employed-retirement-age</value>
      <webElementGuid>c8313f52-3eec-401d-a61f-bdc30a4a2600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4b64f4bb-b843-4267-9397-ae4de922c19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expectedRetirementAge</value>
      <webElementGuid>b6a5bfb3-2391-4621-9611-059eb94913d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>d8c5a340-ebb5-4ed7-9926-b6d88217bbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ec9e940c-8e0f-4973-8181-a5cbf47d20eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-employed-retirement-age&quot;)</value>
      <webElementGuid>704d87d8-933c-4318-9e3c-743dbb10abfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-employed-retirement-age']</value>
      <webElementGuid>21409e02-f900-4950-a835-37e7c685dcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div/input</value>
      <webElementGuid>4c1514cf-2c63-4a1f-91b9-4c513dff28cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-employed-retirement-age' and @type = 'number']</value>
      <webElementGuid>8aa0185f-a996-44a0-bfd4-6e36d68e21bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
