<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter do you receive full stat_7c95a5</name>
   <tag></tag>
   <elementGuidId>3346bcd8-1b80-4b5f-ab9f-761234a2587b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='client1-state-pension-yes'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row.form-group.pl-l.pr-l.ng-invalid.ng-dirty.ng-touched > div.col-8.row > div.input-group.col-8.mr-l > div.form-checkbox > #client1-state-pension-yes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b25e54d-2be9-4131-8848-7ee68952d277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6ddee7eb-d20e-4bd8-b952-07a00e7598f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-state-pension-yes</value>
      <webElementGuid>5b6ad74a-e2bb-4928-a781-d8840442dd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>receiveFullStatePension</value>
      <webElementGuid>5de1e1f8-cfb5-42ae-bc49-f0d7258dd072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a538e62f-57d9-4d6a-ba41-cff54e1e4c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eb6a748a-5caa-402e-bcc9-a74f524338ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>receiveFullStatePension1</value>
      <webElementGuid>a02dcf49-b88c-46cf-b19f-02fae712bed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-create-application[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-l&quot;]/div[@class=&quot;col-12 mt-xl mb-xxl&quot;]/app-tabs[1]/div[@class=&quot;tabs--container row&quot;]/div[@class=&quot;tabs--body col-12&quot;]/app-tab[11]/div[1]/app-retirement-planning-details[1]/div[@class=&quot;container p-0 bg-white box-shadow-grey&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/fieldset[5]/div[@class=&quot;row form-group pl-l pr-l ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;col-8 row&quot;]/div[@class=&quot;input-group col-8 mr-l&quot;]/div[@class=&quot;form-checkbox&quot;]/input[@id=&quot;client1-state-pension-yes&quot;]</value>
      <webElementGuid>880f2875-7cae-490b-95b2-9efc11f923e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='client1-state-pension-yes'])[2]</value>
      <webElementGuid>5bec1742-000a-40a8-a17d-f0a97ebbf67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tab[11]/div/app-retirement-planning-details/div[2]/form/fieldset[5]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>953b51fc-615a-4c52-9cac-21e396888ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-state-pension-yes' and @name = 'receiveFullStatePension1']</value>
      <webElementGuid>258c9e06-f506-4a42-9418-241a35729af4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
