<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_isPoliticallyExposedPerson1</name>
   <tag></tag>
   <elementGuidId>81d2caa3-a05d-4628-8ceb-ab7236c4394e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-politically-exposed-no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1-politically-exposed-no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8c19d6a-8eb9-4ab3-a8f2-1cb1e4dbb967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>03a0dc21-fa88-4254-9e5f-b9a90c9c145d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-politically-exposed-no</value>
      <webElementGuid>b3546e3c-0e13-48ee-a26e-3c37b4944f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isPoliticallyExposedPerson</value>
      <webElementGuid>d965553f-f302-493e-abc9-25822c6fd4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0b7977d5-bf13-474b-8277-0c3c92dcec41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>273ad58e-6eb3-492a-811c-b7676c9ab912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isPoliticallyExposedPerson1</value>
      <webElementGuid>fce69071-d7e8-4176-a47e-1ef1ed23a062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-politically-exposed-no&quot;)</value>
      <webElementGuid>d0bb0311-d918-477d-831b-baea2689d54d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-politically-exposed-no']</value>
      <webElementGuid>3c607bcd-0806-468a-9b30-7c91c1c9a3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/input[2]</value>
      <webElementGuid>1f9b6892-1501-453e-9cfd-aabba4e5496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-politically-exposed-no' and @name = 'isPoliticallyExposedPerson1']</value>
      <webElementGuid>9c1feedf-7420-442b-9184-940537a26011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
