<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passport_verificationIdType1</name>
   <tag></tag>
   <elementGuidId>ffcdfd07-7346-4bc6-a47c-2380cd246456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-driving-licence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1-driving-licence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8841282-003b-4e08-a57f-1ce357b56ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6c9e9169-81fb-4bc3-b280-1db918882cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-driving-licence</value>
      <webElementGuid>00dcdf7c-2d35-4472-a97c-b4257660a8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Driving licence</value>
      <webElementGuid>5316ba6f-bccc-4e0b-acf2-833e4dbc01a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>verificationIdType</value>
      <webElementGuid>f7a0b2f5-9308-452e-8358-af98a5dedb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ml-m ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ea432b53-3602-4431-ab6f-4fd0e07604a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ca10123f-19bb-4f8c-a515-53e908a843fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verificationIdType1</value>
      <webElementGuid>8d8fd15e-4a46-46ae-abb8-d65c7f8aaff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-driving-licence&quot;)</value>
      <webElementGuid>65a33e54-c393-48cd-bd22-96bdbc251c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-driving-licence']</value>
      <webElementGuid>da3ec754-bf5e-4597-8b34-cd8b6e4f1d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div/input[2]</value>
      <webElementGuid>1f8d94b1-6b5c-4acf-9dd5-3ee2e467a4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'client1-driving-licence' and @name = 'verificationIdType1']</value>
      <webElementGuid>c2fb56ff-979f-4f3a-a2e5-e8aa39173197</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
