<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OccupationJob title_client1-employed-_f9375d</name>
   <tag></tag>
   <elementGuidId>14ddbbce-8c37-4fc8-a0ba-ebfd4ac4994b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client1-employed-occupation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1-employed-occupation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16c86282-0daa-4a20-b0b6-0c52e2382726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-employed-occupation</value>
      <webElementGuid>8b8eb6e6-a536-4d5d-b989-bbe44fa08036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11d08b4a-9c57-4870-bb0a-fa480efec8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>occupation</value>
      <webElementGuid>9fb21b45-b340-4efb-b5f2-53d29670d28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>41c5f35a-3098-47dd-be47-c57a3558d21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5b2fbc3c-4893-4678-80a7-86b4e897e46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-employed-occupation&quot;)</value>
      <webElementGuid>bb2599c7-1b6d-4007-beb4-434ff0ff69d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1-employed-occupation']</value>
      <webElementGuid>95c02f47-7095-4b19-bcfc-f9851fa899ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div[2]/input</value>
      <webElementGuid>3cbb4f14-273a-4b87-a4f2-bc60c5790da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1-employed-occupation' and @type = 'text']</value>
      <webElementGuid>9094bbee-9e30-4e6c-9e23-13d5033a12f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
