<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you plan to retire gradually_planT_c71e57</name>
   <tag></tag>
   <elementGuidId>d4942516-80c2-41d7-a92b-be353326be9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='planToRetireGradually-yes'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.ng-invalid.ng-dirty.ng-touched > fieldset > div.row.form-group.pl-l.pr-l > div.col-8.row > div.input-group.col-8.mr-l > div.form-checkbox > #planToRetireGradually-yes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0217d842-cbef-4186-9fa7-06b9cde8f8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3c369e8a-0e38-4bf7-b0fc-63f6b449dc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>planToRetireGradually-yes</value>
      <webElementGuid>21081ec5-21cd-49ca-9c25-173503d28ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>planToRetireGradually</value>
      <webElementGuid>c329fe41-e453-412d-b3d1-ff14adc4fdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c9868a2c-cce4-42d3-a6ae-c9fe5b827c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>625db9c5-0650-47f2-be56-a54a30d6f7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>planToRetireGradually</value>
      <webElementGuid>24e2e0b6-3935-4aff-a0a7-ba2bb2378c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-pale-grey&quot;]/app-root[1]/app-create-application[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-l&quot;]/div[@class=&quot;col-12 mt-xl mb-xxl&quot;]/app-tabs[1]/div[@class=&quot;tabs--container row&quot;]/div[@class=&quot;tabs--body col-12&quot;]/app-tab[11]/div[1]/app-retirement-planning-details[1]/div[@class=&quot;container p-0 bg-white box-shadow-grey&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/fieldset[1]/div[@class=&quot;row form-group pl-l pr-l&quot;]/div[@class=&quot;col-8 row&quot;]/div[@class=&quot;input-group col-8 mr-l&quot;]/div[@class=&quot;form-checkbox&quot;]/input[@id=&quot;planToRetireGradually-yes&quot;]</value>
      <webElementGuid>22fcd214-ae37-47c3-b136-b8853b77bd75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='planToRetireGradually-yes'])[2]</value>
      <webElementGuid>24b908a9-5beb-4d7a-9700-103cf50e8e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tab[11]/div/app-retirement-planning-details/div[2]/form/fieldset/div[2]/div[2]/div/div/input</value>
      <webElementGuid>c6007b6f-c3f8-4e57-8de2-64daba3ce22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'planToRetireGradually-yes' and @name = 'planToRetireGradually']</value>
      <webElementGuid>2bd32640-bfdd-4585-8033-b6454367d1bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
