<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__retirementplanning-client1-pension1S_123f85_1</name>
   <tag></tag>
   <elementGuidId>93224e2c-9744-4572-a718-54db788afd62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value> </value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#retirementplanning-client1-pension1StartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7cede639-c66d-4c8f-94e2-7bbc63456414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56890ed8-b639-4b00-902a-5f8dbecb2c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>0faed417-76fa-4589-ad1d-5fce93787c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter date</value>
      <webElementGuid>4608c241-7802-4643-b812-e5f894517c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(0[1-9]|[12][0-9]|3[01])[-/.](0[1-9]|1[012])[-/.](19|20)\d\d$</value>
      <webElementGuid>89c8cc83-71db-4559-a2ea-af5501f105f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c683904c-7ccc-4483-939e-b9ef63d32ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retirementplanning-client1-pension1StartDate</value>
      <webElementGuid>523d8f97-bcd6-41f1-b780-402fe9b4a264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd20f81d-73e1-4c7b-917f-de0f1c4df7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f45b0d6d-ebf0-4a4b-a544-fb751230853f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retirementplanning-client1-pension1StartDate&quot;)</value>
      <webElementGuid>401ae743-7e8f-4001-beb8-d32f83f7efff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retirementplanning-client1-pension1StartDate']</value>
      <webElementGuid>ec2446a9-2f2e-4322-b03e-86dd15d2ee32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/app-date/input</value>
      <webElementGuid>c517a008-fe14-4dbb-8e2f-a2f23ca23602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'DD/MM/YYYY' and @id = 'retirementplanning-client1-pension1StartDate']</value>
      <webElementGuid>85aec228-94f1-47e8-aaaf-6d5febca6280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
