<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectFull-Time EmployedPart-_fbbedb (1)</name>
   <tag></tag>
   <elementGuidId>807b98a3-628b-47e6-86e6-c4f69d653f23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial experience'])[1]/preceding::select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1-employment-type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4218d416-c210-40be-9956-affabc348d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b997804f-8fa5-4992-a726-f15747cccc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1-employment-type</value>
      <webElementGuid>62af3aee-5468-4cd5-b468-f4efbde392a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11bd1fa5-6d72-4b78-9235-aa3ad774055b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectFull-Time EmployedPart-Time EmployedTemporary/Casual workerSelf EmployedRetiredOther</value>
      <webElementGuid>9c672ff5-0a5e-4c58-8824-a736c50a7265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1-employment-type&quot;)</value>
      <webElementGuid>053dcc6f-83e4-4553-b3bd-afd79b04945a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1-employment-type']</value>
      <webElementGuid>6af3c5e6-eea4-4743-a095-d02663520fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment type'])[1]/following::select[1]</value>
      <webElementGuid>eb7195aa-27e9-4ce3-8a45-6b144cfb4d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment status'])[1]/following::select[1]</value>
      <webElementGuid>8ae848ad-474c-44c3-9731-5d3a0e5e38f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial experience'])[1]/preceding::select[1]</value>
      <webElementGuid>33774612-9764-44f9-a10c-248541636792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approximate stock market investment experience'])[1]/preceding::select[1]</value>
      <webElementGuid>e863ad76-9aa8-49bf-9316-f85230778d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-employment-type/div/select</value>
      <webElementGuid>ec027a26-c9a5-445f-a40a-45b152dc11da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1-employment-type' and (text() = 'Please selectFull-Time EmployedPart-Time EmployedTemporary/Casual workerSelf EmployedRetiredOther' or . = 'Please selectFull-Time EmployedPart-Time EmployedTemporary/Casual workerSelf EmployedRetiredOther')]</value>
      <webElementGuid>7b6020fc-f316-4479-8b12-fb4b88c4b085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
