<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select titleMrMsMrsMissDrOther</name>
   <tag></tag>
   <elementGuidId>937530ac-6cb3-4442-a03d-12e46088eb7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client1title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b4b726db-0159-43b1-b611-65186c5225ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>8b54b425-7f68-49dc-8892-0f2782a58aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1title</value>
      <webElementGuid>ead90842-2648-4872-b000-152765d06847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d51c0ba0-21b5-466b-bb9f-a99457d833de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>573c29d7-7cd9-4667-ab41-e282badabacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select titleMrMsMrsMissDrOther</value>
      <webElementGuid>c6f869cb-4305-4366-81d2-73b647192562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1title&quot;)</value>
      <webElementGuid>4185370d-3903-4e5a-9843-9dee4d3f720d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1title']</value>
      <webElementGuid>9f62d6d9-b349-4242-8daa-a4240679fc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title*'])[1]/following::select[1]</value>
      <webElementGuid>30afb17e-48af-4ff7-88de-a5e77f4f9f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal information'])[1]/following::select[1]</value>
      <webElementGuid>b34b9b1f-4737-4e4d-bf70-f2362820ef37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name/s*'])[1]/preceding::select[1]</value>
      <webElementGuid>c67449c4-8af4-4aed-a711-2d2d7dd5e414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name*'])[1]/preceding::select[1]</value>
      <webElementGuid>445ab415-f8fc-48f3-a709-6eb3e123bbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/select</value>
      <webElementGuid>6d98293a-b147-4b48-91a4-9fe9aaa6cd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1title' and (text() = 'Select titleMrMsMrsMissDrOther' or . = 'Select titleMrMsMrsMissDrOther')]</value>
      <webElementGuid>3c321314-c971-467a-8661-c98400c41782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
